### ISSUE TITLE
Serverside Achievements.

### ISSUE THREAD

**Issue by DragonVV** [gibbed/SteamAchievementManager#10]
Is there really not the slightest chance of unlocking the server side achievements? After all, you do not need to try to unlock them on the server itself, you just need to send the Steam to the required package with the data ... Maybe you can create a temporary server that emulates the game or something like that? One such example is the dull browser game My Lands, I accidentally got an achievement in it and now I'm trying to get 100% for two years. The most interesting thing is that the achievements can be reset through SAM and they really all are blocked in the Steam, maybe you can get the chance to unlock them? I'm even ready to pay for it ...

**Comment by gibbed** [comment]
Attempting to circumvent such "protection", no matter how weak or strong it is, shows clear intent which I have no desire to do. That is not a feature I will personally develop or merge into master.

😓

**Comment by DragonVV** [comment]
There is no hope for the appearance of such a feature in the future?

**Comment by gibbed** [comment]
Not from me.

**Comment by DragonVV** [comment]
Very sorry. Maybe someday you'll change your mind.

**Comment by gibbed** [comment]
No need to apologize! This is just something I set out to do when they introduced protected achievements and I've found no reason to change my mind on it since.
