### ISSUE TITLE
failed to start sam.game.exe

### ISSUE THREAD

**Issue by vvinit** [gibbed/SteamAchievementManager#101]
i just downloaded this and as i tried to run a game it says "failed to start sam.game.exe". i went into properties and unblocked it but i am still having this problem. i do not have any anti-virus installed but i do have one for blocking ads, is that what is stopping it from launching my desired game? or is it something else?

**Comment by tooruu** [comment]
Run it from the same folder

**Comment by vvinit** [comment]
thank you it worked

**Comment by Hi3kari** [comment]
> Run it from the same folder



what if it still doesn't work
