### ISSUE TITLE
Risk of Rain 2 missing achievements

### ISSUE THREAD

**Issue by weblue** [gibbed/SteamAchievementManager#103]
Risk of Rain 2 achievements and stats do not show up. Not sure of the cause, but other games are able to open in SAM normally.

**Comment by PersonalProxy** [comment]
Risk of Rain 2 does not have any Steam Achievements currently.
If you look on any game page, say the original [Risk of Rain store page](https://store.steampowered.com/app/248820/Risk_of_Rain/) you'll see on the right side-bar is says "Includes 15 Steam Achievements" with a link to the [global achievement stats page](https://steamcommunity.com/stats/248820/achievements) for the game.

You'll then notice that the [Risk of Rain 2](https://store.steampowered.com/app/632360/Risk_of_Rain_2/) store page does not have this information. I assume they'll be added later, likely when the game leaves early access.

**Comment by gibbed** [comment]
https://steamcommunity.com/stats/248820/achievements

What?

**Comment by gibbed** [comment]
Yeah, they must have achievements on the backend in Steamworks and this is why it's flagged as having achievements.
