### ISSUE TITLE
Make it work again for Dead by Daylight

### ISSUE THREAD

**Issue by czonta1996** [gibbed/SteamAchievementManager#104]
Sam Picker doesn't work anymore for Dead by Daylight since patch 2.6.0 come out. Rank pips can't be modified. Currently I'm locked at Rank 2 as killer where I have to wait more of 45m to find a match. Fix this tool so I can go back to Rank 8 to prevent this waiting time please

**Comment by gibbed** [comment]
https://twitter.com/gibbed/status/1113253432972828674
