### ISSUE TITLE
Lazily download game logos

### ISSUE THREAD

**Issue by xPaw** [gibbed/SteamAchievementManager#106]
Opening SAM and waiting for it to download 5k icons is no fun, perhaps it could be changed to only download icons for games in view?

**Comment by gibbed** [comment]
Definitely possible, it downloading everything immediately is a holdover from when SAM was originally made and there weren't 5k icons to download. :smile:

**Comment by Chaython** [comment]
IDK what internet you have, but for me all the icons pop in within 100ms. They're set to asynchronously load...

**Comment by Chaython** [comment]
On a side note, steam itself doesn't lazy load images, nor cache them; so every-time you launch it streams them in....
