### ISSUE TITLE
Looks like showing only one empty game.

### ISSUE THREAD

**Issue by jerry1337** [gibbed/SteamAchievementManager#11]
I used 6.3 hotfix version of program and it missed some games.
It recognized all games I have but not showed some of them.

I downloaded latest version but I cannot see my games except one weird game which is not even available on Steam. Then I used game ID to add game, but it cannot add games but shows only one game per search. Something went wrong :(

Is there any quick method to add my own multiple game IDs in setting file?
I don't have any knowledge about coding, but if there is thing that I can modify with wordpad or notepad, I'll try it out !

**Comment by gibbed** [comment]
It's because my server is down at the moment, so the game list download is failing.

Sorry for the trouble. It'll be back as soon as I am able.

There's no way to currently add multiple games at once, something for the future, perhaps.

**Comment by jerry1337** [comment]
Oh, was it server sided? Never expected that tho..
Thanks for the reply. I use this program very very well.

👍

**Comment by gibbed** [comment]
There's no API in Steam to iterate owned games, so I have a huge list of games that have achievements, and SAM checks every single ID to see if you own them.
