### ISSUE TITLE
Unable to commit incremental changes.

### ISSUE THREAD

**Issue by S0T0** [gibbed/SteamAchievementManager#116]
Might be something done of Valve backend as me and multiple people so far in my discord server including myself can't commit number changes anymore.

However achievements are committed just find without any issues.

No error are logged so maybe Valve has locked it for now due to the event, not sure. Was working fine yesterday.

**Comment by gibbed** [comment]
You're going to have to be more specific than that. What game has the problem?

**Comment by S0T0** [comment]
> You're going to have to be more specific than that. What games have the problem?

Seems to be every single game won't save statistics. After quick test for example;
PUBG
Terraria
Starbound
Mordhau
Rust
Torchlight 1 & 2
7 Days to die
Chivalry Medieval Warfare
Closures
CS;GO
Insurgency
Infestion: The New Z

None of these will accept statistic commits but achievements work fine.

**Comment by gibbed** [comment]
Working fine here with Terraria. There's something you're not including here.

**Comment by S0T0** [comment]
> Working fine here with Terraria. There's something you're not mentioning here.

https://i.gyazo.com/849e809dbc273c98762aecb6700c52f7.mp4

Quick video. Tried restarting computer, restarting steam. Running both Steam & SAM as admin, etc.

Going to try on secondary account to see if it's still a issue.

**Comment by gibbed** [comment]
Are you hitting the store button before you confirm your edit in the data list?

**Comment by S0T0** [comment]
> Are you clicking the commit button before you confirm your edit in the data list?

Yeah I was pressing Enter before committing the changes. I went ahead and logged onto my alt account and it worked normally. Relogging back into my main steam account it also worked again.

Not sure what could of caused the issue but having anyone relog into their Steam account seems to have fixed us not being able to commit statistics.

Sorry for wasting your time, probably should of tried that as-well before opening a ticket. (Bought you a coffee to hopefully make up for it 😄 )

**Comment by gibbed** [comment]
This is a UI issue. You were editing the value, then while the edit was active, clicking Commit. You need to confirm the edit (press enter, or click somewhere on the data list) then click Commit.

**Comment by gibbed** [comment]
For further clarity in case anybody else stumbles upon this issue as well:

Basically, if you see this pencil icon when clicking Commit, you're going to lose whatever change you're making:

![Region](https://user-images.githubusercontent.com/85170/60401999-fdd72300-9b4e-11e9-91c6-7c03f3c8fe4d.png)

Confirm the edit by pressing enter or clicking somewhere else on the data list.
