### ISSUE TITLE
No games listed other than Spacewar

### ISSUE THREAD

**Issue by ICantSeeIt** [gibbed/SteamAchievementManager#12]
Using version 7.0.10 downloaded today (though issue was also present in some older version from gib.me/sam).

After a long delay, Spacewar shows up but no other games, and games can't be added (says I don't own them).  Games would show up very quickly before.

Steam is running with the intended Steam user logged in.  No games are running.  Have completely exited Steam (both through Steam menu and Task Manager) and relaunched it with no change.  Also rebooted my computer and saw no change.  Tried downloading this newest version when this happened in the old version I had installed, no change.

Any other steps I can try?

**Comment by gibbed** [comment]
It's because my server is down at the moment, so the game list download is failing.

Sorry for the trouble. If you enter a game you do own, that *should* work however.

**Comment by ICantSeeIt** [comment]
Just got adding a game to work, not sure why it wouldn't work that way earlier.  Must have typed the ID wrong.

Thanks!
