### ISSUE TITLE
Failed to start SAM.game.exe.

### ISSUE THREAD

**Issue by 2002luis** [gibbed/SteamAchievementManager#124]
Antivirus is disabled, I extracted all the files in the zip, none of the files are "read only", steam open, games closed, .NET framework up to date, run as administrator (SAM.Picker) and everytime I choose any game, installed on my pc or not, it will say Failed to start SAM.game.exe. Any idea what could be causing this? They aren't in steam forlder but they are in the same folder

**Comment by 2002luis** [comment]
tried reinstalling and nothing happened

**Comment by gibbed** [comment]
What Windows version?

**Comment by 2002luis** [comment]
Windows 10
I moved it from a folder in the desktop to a folder in my D: drive (my hard drive) and then it started working.
