### ISSUE TITLE
Help on Dead by Daylight

### ISSUE THREAD

**Issue by SSJChris21** [gibbed/SteamAchievementManager#13]
I am trying to set rank to just 15, and I know that to give yourself rank 1, you change the number in SAM to 90.  So I did math stuff to try to find out what number rank 15 would be.  I did 90 divided by 20 (20 ranks in game), which is 4.5.  4.5 times 15 (my wanted rank) equals 67.5.  So I tried entering this number in SAM but I get a red alert icon next to the box and cannot store items.  Why is this? I want rank 15 because I don't want to go all the way to rank 1 just like that.  And I always get paired with people that are new since ranks are reset monthly I think and always end up dying because of teammates.  (I'm not trying to say I'm better than all of them)

**Comment by gibbed** [comment]
It's probably an integer, not a float.

**Comment by SSJChris21** [comment]
I've never used SAM.  Can you explain to me what you just said means.  Thanks and sorry.

**Comment by SSJChris21** [comment]
Ok thanks, it works now lol.  I feel dumb.

**Comment by gibbed** [comment]
Great.
