### ISSUE TITLE
Failed to load schema.

### ISSUE THREAD

**Issue by oberknezev** [gibbed/SteamAchievementManager#143]
I can get into my library but when I try to open a game, I get this error.

**Comment by gibbed** [comment]
Hmm, that would suggest it can't find a file that Steam should be creating.

`C:\Program Files (x86)\Steam\appcache\stats`

Does this directory exist for you? (if you have Steam installed in a different location, then adjust accordingly).

Are all games failing or just a specific one?

**Comment by oberknezev** [comment]
Yes, I have that folder. 
All games are failing.
I'll try to reinstall steam, maybe that's the problem.

**Comment by gibbed** [comment]
Do you have any files named similar to `UserGameStatsSchema_440.bin` in that directory? (not the ones that start with `UserGameStats_`).

Can you give an example of a game that is failing?

**Comment by oberknezev** [comment]
OK, after steam reinstall, it's working, still not sure what was the problem.

**Comment by gibbed** [comment]
That's odd, but glad you were able to solve it.

**Comment by cleirbun** [comment]
Hellooo!!! i have the same problem, and im using the program 3 years without problems :(

**Comment by Conickk** [comment]
Guys, mine also had this same problem in all games, I did the following... you download the game you want the achievements and it will appear there, simple. It worked 100% for me, I hope it helped! Stay cool brothers
