### ISSUE TITLE
Only showing one game!!! was working fine

### ISSUE THREAD

**Issue by mattyboss16** [gibbed/SteamAchievementManager#145]
Help this has suddenly stopped working was working for the past few days now only showing me one game in the menu, it was working today but has stopped please help

**Comment by mattyboss16** [comment]
I refresh the gameslist nothing, and my steam is opened while its running

**Comment by DJMarramiau** [comment]
Same for me. It's only showing Spacewar for me, not detecting any other game. Was working fine this morning.

**Comment by mattyboss16** [comment]
I've got exactly the same, strange. I was using it fine earlier and it was detecting my games fine then too

**Comment by joycourier** [comment]
I don't even have Spacewar...

**Comment by DJMarramiau** [comment]
Spacewar is an example game that the Steam API offers to devs, it's not an actual game we can buy.

**Comment by Crystalknoct** [comment]
So this no longer works?

**Comment by DJMarramiau** [comment]
We will have to wait for @gibbed to release a fix I guess

**Comment by mattyboss16** [comment]
yeah I guess we'll have to wait for @gibbed to fix hopefully it's sorted soon

**Comment by DJMarramiau** [comment]
For now we can manually add the game we want to unlock achievements from, thats all.

**Comment by mattyboss16** [comment]
is there a way to find out the game id's? can't seem to add the games I want. thanks again everyone

**Comment by DJMarramiau** [comment]
Use steamdb.info, use steam store in your web browser and copy the ID in the URL, Toggle URL in the steam client... There are many ways

**Comment by ElizabethDeWitt86** [comment]
It doesn't work for me either, only "SpaceWar" comes out...

**Comment by LULS1212** [comment]
> Use steamdb.info, use steam store in your web browser and copy the ID in the URL, Toggle URL in the steam client... There are many ways

How to do this?

**Comment by gibbed** [comment]
The server the game list is on, is down at the moment. Sorry! I'll try to get it up again as soon as possible.

**Comment by DJMarramiau** [comment]
> > Use steamdb.info, use steam store in your web browser and copy the ID in the URL, Toggle URL in the steam client... There are many ways
> 
> How to do this?

Enter [here](https://steamdb.info/) and search the game you want. Copy the AppID and add it to SAM

**Comment by LULS1212** [comment]
> > > Use steamdb.info, use steam store in your web browser and copy the ID in the URL, Toggle URL in the steam client... There are many ways
> > 
> > 
> > How to do this?
> 
> Enter [here](https://steamdb.info/) and search the game you want. Copy the AppID and add it to SAM

Thank you very much.

**Comment by gibbed** [comment]
See #152.
