### ISSUE TITLE
only showing "Spacewar"

### ISSUE THREAD

**Issue by xmasonx** [gibbed/SteamAchievementManager#146]
so the reason I got this was to remove achievements I got from a friends world in Terraria so I could get them in my world but when I got this all it showed was "Spacewar" so I tried looking it up on youtube and the internet but nothing, so I'm coming here to ask for help. if you can help me with this that would be great.

**Comment by ElizabethDeWitt86** [comment]
It doesn't work for me either, only "SpaceWar" comes out

**Comment by LJSKU77** [comment]
Same here only show "Space War"

**Comment by gibbed** [comment]
The server the game list is on, is down at the moment. Sorry! I'll try to get it up again as soon as possible.

**Comment by basilandherbs** [comment]
appreciate the update, thanks for your contribution :)

**Comment by Sobollion** [comment]
@xmasonx you can put the ID of game into empty white field and press the button "Add Game", then game appears instead "Spacewar" This works for me, until gibbed fixes the server, you can use this method :)

**Comment by basilandherbs** [comment]
@Sobollion is it safe to do while the server is down? I mean, we won't really know until its back up but just to be cautious.

**Comment by Sobollion** [comment]
@basilandherbs i think its ok, gibbed wrote: "The server the game list is on, is down at the moment." its mean that is only game list on this server.

**Comment by Sobollion** [comment]
@gibbed can we use this method, is it safe?


> @xmasonx you can put the ID of game into empty white field and press the button "Add Game", then game appears instead "Spacewar" This works for me, until gibbed fixes the server, you can use this method :)
> P.S. The game ID can be spied in the Steam store by copying the URL. This is a 6 digits number. For Terraria it is 105600

**Comment by gibbed** [comment]
Yes, it's safe. That's what the feature is there for, to add games when they don't normally show up.

**Comment by weehammy98** [comment]
> @xmasonx you can put the ID of game into empty white field and press the button "Add Game", then game appears instead "Spacewar" This works for me, until gibbed fixes the server, you can use this method :)
> P.S. The game ID can be spied in the Steam store by copying the URL. This is a 6 digits number. For Terraria it is 105600

this does not work, it breaks steam completely for some reason.

**Comment by basilandherbs** [comment]
@weehammy98 yeah I can't remove achievements that I ticked. I'll just wait for the servers to come back up.

**Comment by iAmCanonizado** [comment]
I thought I'm just the only one who experience this today. I panicked because I really want to remove spam achievements in my library now. =(

**Comment by iAmCanonizado** [comment]
Adding id of the game works for me. thanks for the suggestion! =)

**Comment by gibbed** [comment]
See #152.
