### ISSUE TITLE
SAM not working.

### ISSUE THREAD

**Issue by Bruhmomentxd** [gibbed/SteamAchievementManager#148]
I was using SAM for a while now but yesterday it just went completely blank randomly. It only shows spacewar and nothing else. What can I do with this? I read that maybe the servers are down and if that's the case how long is it to make them work again? I wanna use the program again.

**Comment by gibbed** [comment]
For the time being you can search for your game on (SteamDB.info)[https://steamdb.info/] and use the App ID from that game's page to manually add it in SAM.

**Comment by Bruhmomentxd** [comment]
Thank your so much for your help!

**Comment by gibbed** [comment]
See #152.
