### ISSUE TITLE
Steam is not running. please run steam error

### ISSUE THREAD

**Issue by sneekii** [gibbed/SteamAchievementManager#15]
i tried to open it. but it gives me this error please help?

**Comment by fbuireu** [comment]
Did you tried to do what error says? To run this tool you have to:
- Open Steam
- Open SAM

Simply as that.

**Comment by gibbed** [comment]
You need to run SAM with the same user/credentials that Steam is running at. So if you're running Steam as admin, you need to run SAM as admin as well.

**Comment by v1shn** [comment]
this does not work

**Comment by bmendonc** [comment]
did you try to reinstall steam?

**Comment by v1shn** [comment]
i opened the next day and it started working... idk, maybe the computer rebooted during sleep mode. anyway, at first i didn't think to restart the computer, because in the previous version of the application for the first time it worked and without rebooting. i forgot to write about it. thank you.

**Comment by gibbed** [comment]
Great.
