### ISSUE TITLE
Achievement protected and cannot be managed.

### ISSUE THREAD

**Issue by Liuksas** [gibbed/SteamAchievementManager#156]
Trying to unlock few achievements I have in game but not in steam. Getting error. Anything I can do?
"Sorry but this is a protected achievement and cannot be managed with steam achievement manager."

Game RF4. (Russian fishing 4)
![Problem](https://user-images.githubusercontent.com/20657921/81674328-a899bc80-9455-11ea-9d0a-6aadee0401bb.PNG)

**Comment by gibbed** [comment]
It means there are servers involved with this game, which are allowed to unlock achievements. And the Steam client cannot unlock them directly.

There is no fix, sorry.
