### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by Preisschild** [gibbed/SteamAchievementManager#16]
Hey guys, please add linux support or if you already have please write in the README how to install or on your website

**Comment by gibbed** [comment]
Direct Linux support probably won't be a thing, however, there is a project that might make it possible via running SAM with Mono + WINE?

https://github.com/sirnuke/steambridge

**Comment by bmendonc** [comment]
well, he could just run steam through wine and then SAM through wine and that would probably work, just make sure you run both applications at the same permissions

**Comment by HeatedTea** [comment]
@bmendonc I recall trying this very thing long ago and I couldn't get it working. I just keep a Windows box around for using SAM and various other utilities, but I'm always seeking to reduce my reliance on Windows so a native Linux port would certainly be welcome if anyone has the time to do it.

**Comment by bmendonc** [comment]
@HeatedTea Did you install the correct prereqs as I remember that SAM has prereqs but I don't remember them exact. Not 100% sure but I thought that some version of the .NET Framework was required.
