### ISSUE TITLE
You still can get VACed,right?

### ISSUE THREAD

**Issue by Peasantly** [gibbed/SteamAchievementManager#17]
Well obvsly I dont know cuz I'm stupid af

**Comment by gibbed** [comment]
A VAC ban for what, using SAM? I've not seen any evidence this has happened to anyone for just using SAM.

**Comment by Peasantly** [comment]
I mean using SAM on vac-secured games such as tf2, cs etc. So is it possible to get VACed by unlocking achievements in these games?

**Comment by gibbed** [comment]
Again, I have not heard of anyone receiving a VAC ban for using SAM. To be absolutely safe, do not use SAM while the games are actually running.
