### ISSUE TITLE
Sorry for annoying, question about Steam "ban"

### ISSUE THREAD

**Issue by Dominik5412** [gibbed/SteamAchievementManager#186]
So im scared as hell. I read pretty much about SAM now and im still not sure if I should use it. The thing is, im convinced that its safe for now, Ive already tried it on my second steam account and did it as obvious as I can, 2 Months later and nothing happened yet. But what makes me really doubtful is the future, maybe the change something in their policy/rules or whatever, and I could get "banned" afterwards.

I dont want to lose my account, Ive spend so much money and time in it, I just want to use it for broken achievements or something like that. And like I said, Im done searching for it, the only thing thats left to seek for kinda answers is here. Would be thankful for answering me.

Greetings

**Comment by gibbed** [comment]
I can't make any guarantees. The only thing I can say is that SAM has existed since 2008 and I have never heard of any ban connected to usage of SAM.

**Comment by HariAcidReign** [comment]
I think it's pretty safe. I used it a LOT during the 2012-13 timeline and kept it very obvious for a long time before removing the achievements and starting legit. Havent heard of anyone getting banned either. But take my advice with a pinch of salt 😄

**Comment by ToadCast** [comment]
There is no guarantees as gibbed says. If you're goal is only for some broken achievements, you should contact the support (Steam or game developers) to fix it. Or check online for a better solution.

I recently had an issue with a 2009 game, an achievement as well, but the community worked with ex-developers of the game on a solution to make it work. If you're not lucky about that, just make up your mind to use it or not.

To be closed?

**Comment by Joshiah12** [comment]
how about running SAM while in VAC secured server??

**Comment by ToadCast** [comment]
> 
> 
> how about running SAM while in VAC secured server??

That cannot happen because when you run it and pick a game, you cannot be playing the game at the same time.

**Comment by Joshiah12** [comment]
> > how about running SAM while in VAC secured server??
> 
> That cannot happen because when you run it and pick a game, you cannot be playing the game at the same time.

i mean pick game like dota,tf,etc but not csgo so i play it while SAM was run

**Comment by ToadCast** [comment]
> 
> 
> > > how about running SAM while in VAC secured server??
> > 
> > 
> > That cannot happen because when you run it and pick a game, you cannot be playing the game at the same time.
> 
> i mean pick game like dota,tf,etc but not csgo so i play it while SAM was run

You cannot launch two games at once.
