### ISSUE TITLE
Is it possible to reset time played to zero/null?

### ISSUE THREAD

**Issue by PaulNevada** [gibbed/SteamAchievementManager#189]
I ask this for the games which are older then 14 days and aren’t gonna be refundable.

**Comment by gibbed** [comment]
You cannot interact with unowned apps whatsoever via Steamworks API.

**Comment by PaulNevada** [comment]
No. I meant here that I ask this for my games which I am not gonna return in future.

**Comment by PaulNevada** [comment]
Meaning this request isn’t for making the app returnable.

**Comment by gibbed** [comment]
That's what I'm saying, even if there was a way to reset it, it would require you to still own it on Steam.

**Comment by PaulNevada** [comment]
So it’s not possible? Steam API allows to manage achievements and doesn’t allow to edit time played?

**Comment by gibbed** [comment]
No, time played is an automatic functionality of the Steam client. There's no Steamworks API for it.

**Comment by ToadCast** [comment]
I guess this issue can now be closed?
