### ISSUE TITLE
ADD HOURS

### ISSUE THREAD

**Issue by Harry007fv** [gibbed/SteamAchievementManager#199]
I wanted to know if we could boost his playing hours, and if we risked being banned from steam.

**Comment by gibbed** [comment]
There's nothing in the Steam API that would allow arbitrary boosting of hours. The only thing you can do is actually idle the time with a given game (or something pretending to be that game) open.

I am not Valve, I cannot say for certain if they would ban for anything. That being said, I've never heard of any legitimate cases of Valve banning (VAC or otherwise).

**Comment by Harry007fv** [comment]
low it's weird there are profiles that have 100,000 hours of games on a single game and 1,800,000 hours in total like him https://steamcommunity.com/id/dohuytuong/?utm_source=SteamLadder.com how did he do that?

**Comment by Harry007fv** [comment]
and also if a steam account is banned, will the other steam accounts present in the house or having the same connection be banned as well or it is just per account.

**Comment by gibbed** [comment]
I didn't say it was impossible to manipulate hours somehow, just that the Steam API, which SAM uses, does not provide such functionality.

I don't know about anything how Valve handle bans.

**Comment by SebiTalent04** [comment]
You can use [Idle Master Extended](https://github.com/JonasNilson/idle_master_extended) for adding hours in games.

**Comment by PaulNevada** [comment]
> You can use [Idle Master Extended](https://github.com/JonasNilson/idle_master_extended) for adding hours in games, without having them installed.

And is there a way do erase/decrease them to 0?

**Comment by SebiTalent04** [comment]
> > You can use [Idle Master Extended](https://github.com/JonasNilson/idle_master_extended) for adding hours in games, without having them installed.
> 
> And is there a way do erase/decrease them to 0?

Umm
I don't think so.
