### ISSUE TITLE
Ban?

### ISSUE THREAD

**Issue by kokorog** [gibbed/SteamAchievementManager#200]
Is it bannable in 2021?

**Comment by Harry007fv** [comment]
wait to hear from the founder or from a guy who still uses it, I advise you not to use it on vac games.

**Comment by Harry007fv** [comment]
what you can also do is talk to a steam moderator or directly through the support (mail) and ask them if you can get banned from steam not games but steam, like that you know.

**Comment by aidsbmx** [comment]
Been using this since 2016, No issues with VAC or any other bans. don't think steam cares TBH

**Comment by Chaython** [comment]
Someone asks this every other day, if you're worried don't use the tool, no one cares about your achievements.

**Comment by ipss1337** [comment]
Just got banned for using this on my alt with connected phone number to my main account
https://steamcommunity.com/profiles/76561199129406305/stats/CSGO

**Comment by gibbed** [comment]
@ipss1337 If you were VAC banned for SAM, then you had to have run it while CSGO was actively running. Which has always been something I've advised against doing.

An alternate account just for CSGO is strange. I'd find it unlikely it was SAM in the end.

I've removed the profile link from your comment because it is advertising a questionable site in the profile name.

**Comment by Firefox289** [comment]
if youve found this yourself dont just do this yourself go youtube search SAM Steam tutorial or something because you wont know how to use it and will probably be banned

**Comment by Joshiah12** [comment]
> Been using this since 2016, No issues with VAC or any other bans. don't think steam cares TBH

how about now?  and how about running SAM while in VAC secured server??

**Comment by Chaython** [comment]
> > Been using this since 2016, No issues with VAC or any other bans. don't think steam cares TBH
> 
> how about now? and how about running SAM while in VAC secured server??

As stated many times, it's ill advised to run this on a vac secured server, this interacts with the steam.dll, and most hacks are done via script injection/execution, so most anticheats will ban you if your process interacts with the game's DLLs.
Process hacker is a powerful task manager, and you get banned for using it in many games, despite not using it to interact with anything....
