### ISSUE TITLE
Locked achievements??

### ISSUE THREAD

**Issue by Igo-Cigo** [gibbed/SteamAchievementManager#201]
Any way to get them with sam?

**Comment by ToadCast** [comment]
I'm not sure what you ask for. If you meant the Hidden achievements, displayed like below:
![image](https://user-images.githubusercontent.com/31543450/108710661-473a6a00-750c-11eb-97a4-1baf26ebba17.png)
SAM can unlock them, yes.
If by locked you mean stuck, I would say no.

**Comment by FliaXz** [comment]
You mean protected achievements? because they can't get unlocked by SAM.
