### ISSUE TITLE
Yakuza 3-5 aren't showing up 

### ISSUE THREAD

**Issue by SaintoNikk** [gibbed/SteamAchievementManager#207]
Hey
Recently bought the remastered collection and currently stuck with an annoying achievement in 3, wanted to use SAM to get over with it but 3 and the rest of the remastered games won't show up
The rest of the Yakuza games (0,kiwami 1+2 and 7) do show up and everything works fine

**Comment by gibbed** [comment]
Should be fixed now. The cron script responsible for checking for new games wasn't reporting an error as it should have been.

**Comment by SaintoNikk** [comment]
> Should be fixed now. The cron script responsible for checking for new games wasn't reporting an error as it should have been.

Thank you for the quick fix!
