### ISSUE TITLE
Sam not detecting game phasmophobia

### ISSUE THREAD

**Issue by AnyLastWords** [gibbed/SteamAchievementManager#210]
I have tried putting in the steam is but when I get to the game on Sam I get this issue generic issue. I attatched a screenshot showing I own the game on steam. I have tried restarting my pc redownloading the game trying beta mode and it wont detect it.
![image](https://user-images.githubusercontent.com/68654921/111568329-8c019b80-876e-11eb-9cf1-174399edd317.png)

**Comment by gibbed** [comment]
This game doesn't have achievements currently.

**Comment by AnyLastWords** [comment]
I guess it doesnt i just realized how stupid I am
