### ISSUE TITLE
VAC on lobby??

### ISSUE THREAD

**Issue by Joshiah12** [gibbed/SteamAchievementManager#214]
So by accident I forgot to turn off SAM while running Dota 2, but was just in the lobby, I immediately closed SAM and didn't know if in the future I would get VAC bans?

**Comment by gibbed** [comment]
I'm not Valve.

**Comment by Chaython** [comment]
> So by accident I forgot to turn off SAM while running Dota 2, but was just in the lobby, I immediately closed SAM and didn't know if in the future I would get VAC bans?

If you're going to get banned it usually happens immediately.
I had ran this while in game without issue, but just be careful in the future.
Lobby shouldn't be important but you never know.

**Comment by Joshiah12** [comment]
> > So by accident I forgot to turn off SAM while running Dota 2, but was just in the lobby, I immediately closed SAM and didn't know if in the future I would get VAC bans?
> 
> If you're going to get banned it usually happens immediately.
> I had ran this while in game without issue, but just be careful in the future.
> Lobby shouldn't be important but you never know.
> There's so many duplicate posts of this, why create another?
> IDK why people are so lazy 'n dumb.

Sorry mate, cause I don't wanna waste my time finding another old post. And here I know you will answer me so that's what I want ty.
