### ISSUE TITLE
Sam Functionality

### ISSUE THREAD

**Issue by theoogleking** [gibbed/SteamAchievementManager#216]
So I am not a coder and have only dabbled in very basic programming so I likely will not understand any more succinct explanations of my question. My question being, what does SAM do exactly? I've read elsewhere that it fakes achievements. I'll assume that just means that it fakes the requirements for the achievement, but does it actually show up on steams end and that data is collected? And if you were to do this multiple times would it send it again every time and accumulate data? As in have the same achievement data counted more than once as if you were playing from a fresh account. Or does it retract that data and send it again. Sorry if my question is confusing.

**Comment by gibbed** [comment]
Achievements don't have requirements on Steam, they are simply either unachieved or achieved. SAM simply interfaces with Steam to update state for various games.
