### ISSUE TITLE
Cant remove an achievement using sam?

### ISSUE THREAD

**Issue by PerfectEvil** [gibbed/SteamAchievementManager#217]
https://user-images.githubusercontent.com/77389973/124386490-9c646480-dcd2-11eb-9c13-86cf65df735c.mp4

I cant remove the deceit achievements or reset them with stats.

**Comment by MysticJames** [comment]
mmm umm proby just a error in the code but i do have a remastered version of it because sadly sam isn't going to be updated no longer

**Comment by PerfectEvil** [comment]
> mmm umm proby just a error in the code but i do have a remastered version of it because sadly sam isn't going to be updated no longer

What remastered version?

**Comment by MysticJames** [comment]
i made a remastered version of sam on my github
