### ISSUE TITLE
It is possible to get banned?

### ISSUE THREAD

**Issue by czSmoG** [gibbed/SteamAchievementManager#219]
It is possible to get banned?
I know this isnt issue but im ask and i dont know how fucking github works

**Comment by MysticJames** [comment]
no steam does not give a fuck about achievements

**Comment by Chaython** [comment]
It has been asked dozens of times, read.

**Comment by MysticJames** [comment]
> 
> 
> It has been asked dozens of times, read.

bruv fuck off

**Comment by WineBartender** [comment]
Depends on the game, some games that has a lot of hard achievements and paid will usually be pretty mad about it. If they decide to ban you or not is up to them. Try looking it up before using it a on game you're not sure about.

**Comment by Chaython** [comment]
No one cares about your achievements besides you and you went to cheat, so it shouldn't matter to you either. 
Just don't run this while in a game. Don't keep this unpacked. Don't use SAM in a game where achievements could actually matter, though I don't know of any. [You could use SAM back when GMG paid people for steam achievements, but they arbitrarily banned people who were earning too much.]
