### ISSUE TITLE
How to remove achievements from removed games?

### ISSUE THREAD

**Issue by hyoretsu** [gibbed/SteamAchievementManager#220]
Simply put, a while back I started giving myself all achievements because yeah. I then regretted that and removed all of them. (I've never played 30/35 of my "perfected games" and I "have" 2,855 achievements)

Is there a way to remove achievements from games that were either deleted from Steam or can't be downloaded anymore? Those don't show up in SAM, and you get "You don't own that game." error when trying to add them.

Sadly this seems abandoned.

**Comment by gibbed** [comment]
You can't interact with such games via the API.

SAM isn't abandoned, it's feature complete. No future updates are planned beyond contributions that I find acceptable.

**Comment by hyoretsu** [comment]
Do you know of some other way to remove those kinds of achievements or am I stuck with them?
