### ISSUE TITLE
Keep getting error on steam login when opening games on SAM picker

### ISSUE THREAD

**Issue by MiloDaCat** [gibbed/SteamAchievementManager#221]
every time I click the game on SAM picker, it doesnt show any achievements and steam says my account credentials have been changed as well, I have to relogin and I cant use SAM. does anyone know how to fix this?

**Comment by gibbed** [comment]
I've never heard of this specific interaction, are you running Steam elevated as administrator by any chance?

**Comment by MiloDaCat** [comment]
I dont believe so I just opened it normally

**Comment by MiloDaCat** [comment]
when I try to relog, it just says that theres a computer logged into my account somewhere and I have to type in my password again

**Comment by MiloDaCat** [comment]
Ive been trying to set up ASF achievement but im not sure how that works either, I just want to change my achievements :(

**Comment by marosmihalek** [comment]
I must agree. Now I tried it 2 times and 2 times same problem. I was scared that somebody changed my password, lol.

**Comment by marosmihalek** [comment]
**FIX: Turn off your hour booster/exit steam & turn off all the games.**
