### ISSUE TITLE
An error occurred while setting the value for GMA_X_MINUTES_STAT, aborting store.

### ISSUE THREAD

**Issue by DominicFilice** [gibbed/SteamAchievementManager#222]
When trying to change the value of time for my minutes played, I get this error: "An error occurred while setting the value for GMA_X_MINUTES_STAT, aborting store."

Am I being a dumbass? I dont understand what im doing wrong, Im only inputting my original time after accidentally giving my self the one month achievement on Garrys Mod.

![image](https://user-images.githubusercontent.com/50728191/126856777-d37c6b66-bf87-4ffd-a28a-ffbdcbc93ef0.png)

**Comment by gibbed** [comment]
What was the original value?

**Comment by DominicFilice** [comment]
> What was the original value?

375

**Comment by DominicFilice** [comment]
I hadnt noticed until I saw the progress of that achievement, so I played 375 minutes with out noticing.

**Comment by DominicFilice** [comment]
Oh wait were you asking for the original time I had? It shows me my play time which is 833.4 hours but the achievement **isnt** going based off that play time.

**Comment by gibbed** [comment]
It may be a server-only modifiable stat, given that it's for Garry's Mod.

**Comment by DominicFilice** [comment]
Doesnt matter anymore I gave the achievement as I already played 34 days
