### ISSUE TITLE
Old/discontinued game unlocks

### ISSUE THREAD

**Issue by Rolutav** [gibbed/SteamAchievementManager#223]
I've been searching and searching for ways to unlock achievements for old games, three games in particular: 
Super Monday Night Combat, Alliance Of Valiant Arms and Crime Craft Gang Wars. I have the files for SMNC but not the others, steam will not accept any "duplicate" steam keys so I can't put them in my inventory/on my account conventionally. There are two achievements for SMNC, one for AOVA and one for CCGW, I can specify which ones they are. I looked every where to find the version of SAM to unlock achievements from games you don't have and since these games are free, I don't see much harm in it. If anyone can help me out, I've fallen flat/hit a rut and idk what to do.

**Comment by gibbed** [comment]
There isn't a version of SAM that can unlock achievements without first owning the game on Steam. The Steam API does not allow this.

**Comment by Rolutav** [comment]
Could it be possible to unlock specific achievements from a f2p discontinued game?

**Comment by Cristonimus** [comment]
I managed to download SMNC legally in 2021 using steam with the help of a inventory gift
But SAM won't let you put the achievement 
It says something like: "Sorry... blah blah blah... the game is protected... you can't unlock any achievements"
I've been looking for it on the internet, and looks like that is because of the game itself

> There isn't a version of SAM that can unlock achievements without first owning the game on Steam. The Steam API does not allow this.

**Comment by Rolutav** [comment]
> I managed to download SMNC legally in 2021 using steam with the help of a inventory gift
> But SAM won't let you put the achievement
> It says something like: "Sorry... blah blah blah... the game is protected... you can't unlock any achievements"
> I've been looking for it on the internet, and looks like that is because of the game itself
> 
> > There isn't a version of SAM that can unlock achievements without first owning the game on Steam. The Steam API does not allow this.

could you or the person gift the game to me? this would be amazing if you could. My steam friend code is 152375247

**Comment by gibbed** [comment]
> I managed to download SMNC legally in 2021 using steam with the help of a inventory gift
> But SAM won't let you put the achievement
> It says something like: "Sorry... blah blah blah... the game is protected... you can't unlock any achievements"
> I've been looking for it on the internet, and looks like that is because of the game itself

SMNC was a server based game, and its achievements are protected to being unlocked by game servers.
