### ISSUE TITLE
Locking achievements resets all images

### ISSUE THREAD

**Issue by dwseank** [gibbed/SteamAchievementManager#226]
I used the tool to lock some achievements and it set all of the game's achievement images (locked and unlocked) to the locked variant.
The same happened to 3 games I tried locking the achievements for.
When earning an achievement after the fact it shows the correct image but previously unlocked achievements have a locked image while being unlocked.

Here's how it looks (Saints Row: Gat out of Hell):
![achievements](https://user-images.githubusercontent.com/89531857/130812720-c61c89e1-03ac-47e8-8848-9d2ad2a06338.png)

Is there a fix for this?

**Comment by gibbed** [comment]
No, this would be something on Steam's end. You might be able to get around it by doing a full reset of achievements via SAM but I wouldn't recommend that.
