### ISSUE TITLE
SAM Picker won't run/extract

### ISSUE THREAD

**Issue by bestpwnage** [gibbed/SteamAchievementManager#229]
![image](https://user-images.githubusercontent.com/90241438/132299404-063c568b-1514-48ff-bb08-bf95a8eea8e5.png)

![SAM error](https://user-images.githubusercontent.com/90241438/132298927-ad7788b1-d6f3-4b58-919e-8e4b6638acbb.PNG)

When I extract the zipped folder, SAM.Picker is either not included in the extracted folder or, when it is and I am able to attempt to run it, I get this error.

**Comment by Elry-Moe** [comment]
Your Antivirus is deleting the file.
