### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by techsimmons** [gibbed/SteamAchievementManager#23]
Windows Defender found a severe Trojan in this download Win32/Scrarev.C.

I do not notice any negative computer effects, but it has been quarantined.

**Comment by Bilge** [comment]
Congratulations on your open source trojan discovery.

**Comment by gibbed** [comment]
It's very likely it's a false positive. Builds are automatic through AppVeyor.

**Comment by ElPumpo** [comment]
Searched against Defender 1.259.938.0 (2017-12-29), it found nothing - this issue can be closed.
