### ISSUE TITLE
An older issue has appeared again ("Spacewar")

### ISSUE THREAD

**Issue by LordLutz** [gibbed/SteamAchievementManager#235]
Hello Mr. gibbed,
I read about the following issue and that you are working for a solution. Yesterday, the 16. of Nov. 2021, it happened again:
Only 1 game pops up in SAM, it´s name is "Spacewar", but I don´t own this.

Is there anything I could do at myself to repair this or can you patch it ?
I would appreciate your help and until any solution I will work with single app-id´s - the only way it works in the moment.

Bye, it would be nice to hear from you.

**Comment by gibbed** [comment]
Everything is in #152, I have nothing to say about it that changes from what's said there.

**Comment by LordLutz** [comment]
Thank you !

**Comment by butterfliex** [comment]
> Hello Mr. gibbed, I read about the following issue and that you are working for a solution. Yesterday, the 16. of Nov. 2021, it happened again: Only 1 game pops up in SAM, it´s name is "Spacewar", but I don´t own this.
> 
> Is there anything I could do at myself to repair this or can you patch it ? I would appreciate your help and until any solution I will work with single app-id´s - the only way it works in the moment.
> 
> Bye, it would be nice to hear from you.


This is happening again as of 11.10.2023 :/

**Comment by butterfliex** [comment]
> It should be resolved as of a few minutes ago.

Works, thank you king.
