### ISSUE TITLE
Steam Achievement Manager does not work

### ISSUE THREAD

**Issue by LosIvanos** [gibbed/SteamAchievementManager#238]
Hi friends,

today 20.11.2021 I found out that Steam Achievement Manager v7.0.25 does not work.
Does not load any of the games in the steam library at startup :(
I believe that this problem will be solved soon :)

**Comment by ThiandaS** [comment]
I think steam actually patched it :(

**Comment by gibbed** [comment]
SAM still works, please refer to #152.

**Comment by LosIvanos** [comment]
When I add an App ID, everything works.
Thank you for the information.
