### ISSUE TITLE
Owned game not recognised in SAM (Metro LL)

### ISSUE THREAD

**Issue by ddpph** [gibbed/SteamAchievementManager#243]
Hello, here is the issue.

Upon attempting to use SAM with Metro LL: Redux (specifically by adding the game manually with an ID, since I am experiencing the 'Spacewar' issue right now), SAM says "Game not owned".

This is incorrect, since I have played the game for 20 hours myself up to date. This issue doesn't seem to happen with other games in my library. My Steam is not Offline when I attempt to do this. 

Any feedback is appreciated

**Comment by gibbed** [comment]
Which app IDs have you tried?

**Comment by ddpph** [comment]
39996 is the one I can find on SteamDB about Metro LL. Otherwise this is the only I have tried

**Comment by gibbed** [comment]
I'm not sure how you got `39996`.

https://steamdb.info/search/?a=app&q=metro+last+light&type=1&category=0

Its app ID should normally be `287390`.

**Comment by ddpph** [comment]
> I'm not sure how you got `39996`.
> 
> https://steamdb.info/search/?a=app&q=metro+last+light&type=1&category=0
> 
> Its app ID should normally be `287390`.

Hm, your code does work - I'll write this off as my inattentiveness.  Thanks
