### ISSUE TITLE
Stopped working?

### ISSUE THREAD

**Issue by AnotherGuyHere** [gibbed/SteamAchievementManager#246]
Hi, I used it a few months ago and it worked fine, now when I start I don't see any game, is it my problem or the same thing happens to you? Thx :p

**Comment by BANNN911** [comment]
Hi. Everyone has this problem

**Comment by gibbed** [comment]
@BANNN911 No, if you're talking about the recent downtime (#152) that's since been resolved.

**Comment by Homikator** [comment]
It works! Thanks!

**Comment by TechieMan** [comment]
Have anyone had any problem with ''steam bans'' or something along those lines after using this service?

**Comment by MysticJames** [comment]
@TechieMan You will not get banned using SAM or SAMR.

**Comment by BANNN911** [comment]
> @ BANNN911 Нет, если вы говорите о недавнем простое ( [# 152](https://github.com/gibbed/SteamAchievementManager/issues/152) ), которое с тех пор было решено.

thank you very much for your work <3
