### ISSUE TITLE
S.A.M. logs me out from the Steam client and doesn't load any achievements or statistics from a game that i select

### ISSUE THREAD

**Issue by sniperstyx** [gibbed/SteamAchievementManager#252]
I just came back to using this app after a long time so I can fix my Team Fortress 2 stats since I reset them a long time ago after screwing them up and not being able to change them back to how they were before.

Now that I came back to use this app, I opened up the "SAM.Picker.exe" file and looked for TF2. After I found it, I opened it up and then I was prompted by Steam that I've been logged in on another PC, even if I've never used my account anywhere else in the past year but this computer (excluding my phone). I logged back into the Steam client and it gave me the same error over and over. I had to close S.A.M. in order to log back in and now I don't know how to restore my hours on my classes.

Is there any way I can fix this?

**Comment by iBreakEverything** [comment]
Old SAM used to do this. The app is built that way, this is not ASF.

**Comment by Soumyadeep98O** [comment]
Same issue here also!
Have you found any fix?

**Comment by sniperstyx** [comment]
> Same issue here also! Have you found any fix?

For some reason it now works normally. I don't know what happened, but I think it had something to do with launching the app in admin mode or whatever. I can't remember exactly.

**Comment by Soumyadeep98O** [comment]
> > Same issue here also! Have you found any fix?
> 
> For some reason it now works normally. I don't know what happened, but I think it had something to do with launching the app in admin mode or whatever. I can't remember exactly.

Lol, same! Mine also just randomly started working, strange…!
Btw, thanks for the quick reply.

**Comment by sniperstyx** [comment]
> > > Same issue here also! Have you found any fix?
> > 
> > 
> > For some reason it now works normally. I don't know what happened, but I think it had something to do with launching the app in admin mode or whatever. I can't remember exactly.
> 
> Lol, same! Mine also just randomly started working, strange…! Btw, thanks for the quick reply.

Well as soon as I got an email about a reply to my issue, I just went on GitHub and replied lol.
