### ISSUE TITLE
I dont understand

### ISSUE THREAD

**Issue by IMostLikelyHaveAQuestion** [gibbed/SteamAchievementManager#26]
So, this would be my first time downloading a file like this, i cant find the executable file

**Comment by IMostLikelyHaveAQuestion** [comment]
I tried this, 1 download, 2 extract, 3 search everywhere in the folder for something to open

**Comment by lattedesu** [comment]
get the latest zip from releases page:

https://github.com/gibbed/SteamAchievementManager/releases

**Comment by IMostLikelyHaveAQuestion** [comment]
i found the exe but one didn't open, the other disappeared and was just picked up by norton, ive seen things about this being a false positive but i cant get sam.game or sam.picker open

**Comment by IMostLikelyHaveAQuestion** [comment]
wait i think i forgot 2 downloads

**Comment by lattedesu** [comment]
Can't say much.. Works nice on my end. Maybe @gibbed will help you. Make sure runtimes are installed.

**Comment by IMostLikelyHaveAQuestion** [comment]
yeah now that i look at it, source code is probably important, thank you for your help

**Comment by lattedesu** [comment]
You're downloading this file, right?

https://github.com/gibbed/SteamAchievementManager/releases/download/7.0.10/SteamAchievementManager-7.0.10.zip

**Comment by IMostLikelyHaveAQuestion** [comment]
yeah

**Comment by IMostLikelyHaveAQuestion** [comment]
wait this does work for windows 8.1 right?

**Comment by IMostLikelyHaveAQuestion** [comment]
wait, whats runtimes

**Comment by lattedesu** [comment]
They are the executables. Can't say much about Win8.1 but this works nice on Win10. Also should work on both nicely.

**Comment by IMostLikelyHaveAQuestion** [comment]
ok well thank you for your help, i will see if there are any uninstalled files

**Comment by gibbed** [comment]
It does work on Windows 8.1, if you're having issues you should try making sure you have the .NET4 runtime installed.


Though I think Windows 8.1 has that pre-installed.
