### ISSUE TITLE
"Space War" error resurfaced 3/14/2022

### ISSUE THREAD

**Issue by PrinceOfPomp** [gibbed/SteamAchievementManager#262]
This morning, I attempted to use Steam Achievement Manager to correct an achievement that should have popped not unlocking, but, after opening the game in question (Snake Pass), reopening the SAM program merely offered Space War. Now, the previous report of this error mentioned a server migration as the cause, and I'm trying to see if this corrects itself, or if it's something of greater concern

**Comment by Dphantom22** [comment]
Hi. I have the same prob. this day.

**Comment by kai999901** [comment]
me too have prob maybe need update new version?

**Comment by PrinceOfPomp** [comment]
> me too have prob maybe need update new version?

Not sure if it warrants an update; as I mentioned, last time it was a server-side issue. Could be some unexpected downtime.

**Comment by thejacksparrow1** [comment]
Same. sadly. 
never had this before!

**Comment by gibbed** [comment]
Yeah, it's server downtime again. Please refer to #152 for future updates.

**Comment by PrinceOfPomp** [comment]
> Yeah, it's server downtime again. Please refer to #152 for future updates.

Sorry, wasn't sure if it was downtime or some new issue. Thanks for answering!

**Comment by ZekePolarisBSH** [comment]
I am getting this too, and I never played this game before. I hope it works soon. Also, I wonder why out of all the games on Steam, why Space War?

**Comment by gibbed** [comment]
> I am getting this too, and I never played this game before. I hope it works soon. Also, I wonder why out of all the games on Steam, why Space War?

That's the default list of games if SAM fails to download its game list.

https://github.com/gibbed/SteamAchievementManager/blob/7b301fa56acb7f1130a0a2a24368c4f3da3ebe1b/SAM.Picker/GamePicker.cs#L356-L359

**Comment by gibbed** [comment]
Resolved as of yesterday. Please refer to #152.
