### ISSUE TITLE
What the hell is spacewar?

### ISSUE THREAD

**Issue by KLash17** [gibbed/SteamAchievementManager#263]
So I wanted to unlock the rest of the sonic cd achievements, and all that shows up is this game called spacewar? Idk if it is some bug you have but can you please fix it

**Comment by ReaperN** [comment]
It's because the server that SAM pulls its game list from is currently down as of March 14th, 2022. It's pinned on the "issues" page

**Comment by KLash17** [comment]
oh, Sorry I didn't know

**Comment by gibbed** [comment]
Resolved as of yesterday. Please refer to #152.
