### ISSUE TITLE
Changing TF2 class play time to less

### ISSUE THREAD

**Issue by Mysterio27xd** [gibbed/SteamAchievementManager#271]
When I was young, I accidentaly reseted my stats on tf2, So today I decided I'll fix the hours so they match my acctual playtime.
I accidentaly set the value too high and when I tried to lower it it wouldnt work, It is sending error "An error accured while setting the value for Scout.accum.iPlayTime, aborting store". But when I set the value 1 higher, it worked, So it doesnt work only if you wanna lower the value.
![44968ba01f2a1344408032b8daf59e3c](https://user-images.githubusercontent.com/103941346/163813594-591eb69c-f606-4bd5-8026-16d62bc509f1.png)

**Comment by gibbed** [comment]
It's likely an increment only stat.

**Comment by Mysterio27xd** [comment]
> It's likely an increment only stat.

And is there any way to lower it?
