### ISSUE TITLE
Steam games aren't loading

### ISSUE THREAD

**Issue by QuietBushi** [gibbed/SteamAchievementManager#292]
Steam games aren't loading in the Manager. That's about all I can say.

Well one game will load, however, the image won't. It's called Spacewar. I'm trying to get an achievement in Among Us that has bugged out on me, but it as well as every other game just won't load.

**Comment by kolicuch** [comment]
yeah same to me

**Comment by Mockordio** [comment]
Yep, just black background and no games loading.

**Comment by gibbed** [comment]
Please refer to #152.

**Comment by QuietBushi** [comment]
> Please refer to #152.

Thank you thank you

**Comment by Mr-Conspirator** [comment]
> Please refer to #152.

any clue when it will be back up?

**Comment by kowwai** [comment]
games like crimecraft gangwars (servers down) that are family shared to me, can i get the achivment? is it bc of the software or the game? PLEASE lmk <3

**Comment by Danyelalejandro** [comment]
+1
