### ISSUE TITLE
Error edditing games

### ISSUE THREAD

**Issue by diamondlord1000** [gibbed/SteamAchievementManager#30]
it says this for every game I try and load: Error Failed to start SAM.Game.exe. so I have no idea what is wrong or if I just didn't do it right or what someone help

**Comment by gibbed** [comment]
You may need to right-click SAM.Game.exe in Explorer and open Properties, then Unblock it from there. If that doesn't help, your anti-virus may be stopping it from running.

If you try to run SAM.Game.exe directly, what happens?

**Comment by diamondlord1000** [comment]
I can open the program itself but when I pick a game it says it cant open the game (I made a video of it but I don't know how to get it on here)

**Comment by diamondlord1000** [comment]
I'm trying to reset my achievements on human fall flat so I can record a how to get this achievement sort of thing for my yt

**Comment by gibbed** [comment]
There are two executables. Please don't try to run it from the ZIP. Extract it to a folder somewhere first.

**Comment by diamondlord1000** [comment]
moved to its own folder I think its my antivirus if you don't mind me asking why does all of my antivirus say that this is a bad file? will try to look into stoping the antivirus

**Comment by diamondlord1000** [comment]
just opened the file where I moved it to and for once antivirus did not try to stop me I now have four parts in their own file: git-log.txt, LICENSE.txt, SAM.API.dll, and SAM.Picker.exe    when I run the last one it opens without antivirus stopping it but it still has the error from the beginning

**Comment by gibbed** [comment]
Please do as I suggested before:

You may need to right-click SAM.Game.exe in Explorer and open Properties, then Unblock it from there. If that doesn't help, your anti-virus may be stopping it from running.

**Comment by tpressley** [comment]
I just had this same issue. I was able to fix it by changing the install location of SAM to be on my C: drive (which is the drive my OS is on, and the drive Steam is installed on). When I was getting the error, SAM was running from a secondary drive.
