### ISSUE TITLE
Please Clear My Doubt

### ISSUE THREAD

**Issue by GitSeal** [gibbed/SteamAchievementManager#33]
i have some doubts please clear it.
i use sam for idling games only.
i never use it to unlock achievements or modding stats or resetting data.
while sam is running i never try to play any game.

These are my sam running credentials:
1. - first open steam client -change friend visible status from online to offline
2. - than open SAM.Picker.exe product version 6.3.0.987
3. - add 15 steam game app ids one by one - new windows box open
4. - include counter strike 1.6 & dota
5. - Leave process till 5 hours everyday & go to bed & sleep

have a doubt 

am i got Vac Ban For Doing this ?
or
Not ?

please clear my doubts with complete honesty
for your concern i am expanding my steam account level to 1000
i dont want my future investment will be in danger thats why i use words like honesty

Thankyou
Sam user

**Comment by gibbed** [comment]
I've never received any legitimate evidence of anyone receiving any kind of ban over using SAM.

**Comment by GitSeal** [comment]
i am not believe in evidence
peoples use hacks and cs go 
there after blame Sam
i have complete trust on you and your programme.
i am asking to you regard my action

+

one more query should i use updated version 7.0.0.1 or old version 6.3.0.987
my basic need is idling only

**Comment by gibbed** [comment]
Which version, that's your call. There's not that much difference between the versions aside from bugfixes to things that are completely irrelevant to you if you're not using the actual features of SAM.

**Comment by GitSeal** [comment]
ok
one more closing request
can bifurcate steam achievement manager into two parts
1 is achievement manager
2 is idler or farmer

**Comment by gibbed** [comment]
SAM isn't intended for farming, [there's already tools for it](https://github.com/jshackles/idle_master).
