### ISSUE TITLE
No .exe or .Picker ANYWHERE! please help!

### ISSUE THREAD

**Issue by Charbomber** [gibbed/SteamAchievementManager#34]
i can't find the program that RUNS it! please help!

**Comment by azizcrb77** [comment]
me too

**Comment by bmendonc** [comment]
did you download just the source or the compiled version?

**Comment by ElPumpo** [comment]
Really guys? How hard is it to extract the software?! Simply extract the software anywhere on your computer and run any of the two executables.

**Comment by M23Nono** [comment]
ElPumpo, есть скайп?Я не понял, что нужно сделать и у меня нет Exe. Я нажимаю извлечь на рабочий стол и не фига нету Exe /

**Comment by ElPumpo** [comment]
@M23Nono why in russian!? What makes you think any of us understands the language???

**Comment by BaneSRB** [comment]
download from here:
https://github.com/gibbed/SteamAchievementManager/releases/download/7.0.11/SteamAchievementManager-7.0.11.zip

Your welcome
