### ISSUE TITLE
after selecting the game you want to unlock achievements for, it does not open the list of achievements for that game.

### ISSUE THREAD

**Issue by F-16Aircraft** [gibbed/SteamAchievementManager#346]
after selecting a game and double clicking on it, it just re-opens the game selector screen, instead of the games achievements modifiers.

**Comment by xxGreenRoblox** [comment]
Did you double click the game you wanted to change?

**Comment by F-16Aircraft** [comment]
> Did you double click the game you wanted to change?

yes i did, it just reopens the same 'select game' screen
