### ISSUE TITLE
not working properly [BUG](issue solved)

### ISSUE THREAD

**Issue by F-16Aircraft** [gibbed/SteamAchievementManager#353]
after running "SamPicker.exe" the application opens as normal and the games list shows up, but after selecting a game, it does not open the achievements list for that game, it just re-opens the same window that shows a list of all the games. i have tried everything, including trying to get other forks to open the achievement list, for whatever reason, it will not open the achievements list. i have tried disabling every windows security feature including memory integrity, and adding the program as an exception in the windows security settings, and it still wont open achievements list.

**Comment by gibbed** [comment]
That's pretty weird, `SAM.Game.exe` only spawns `SAM.Picker.exe` if it received no arguments on the command-line. You're using standard Windows and such?

**Comment by F-16Aircraft** [comment]
im using the latest version of windows 11

**Comment by F-16Aircraft** [comment]
any fix for it yet?

**Comment by F-16Aircraft** [comment]
> That's pretty weird, `SAM.Game.exe` only spawns `SAM.Picker.exe` if it received no arguments on the command-line. You're using standard Windows and such?

does it require .NET? if so, the only version i have is the latest version of .net, i was unable to install .net4

**Comment by F-16Aircraft** [comment]
> That's pretty weird, `SAM.Game.exe` only spawns `SAM.Picker.exe` if it received no arguments on the command-line. You're using standard Windows and such?
 
hey i think i figured out the issue, i currently do not have ".NET SDK 4.5.2" framework installed which i think could be causing the program to malfunction, i only have .NET SDK 7.0.306(x64) installed, do you think you can update it to support this framework?

**Comment by adrian-coh** [comment]
I have also been getting this same problem. I use the latest version of Windows 11 aswell and wish to know if you have found a solution to this.

**Comment by F-16Aircraft** [comment]
> I have also been getting this same problem. I use the latest version of Windows 11 aswell and wish to know if you have found a solution to this.

i figured out the issue, i had some issues with audio so i reset my pc and selected "keep files"(note: this will delete all of your apps and their settings{if you do this please back up your saved firefox passwords/profile date. look online to figure out how to back up these files}) anyway, when i was updating windows 11 to the latest version i noticed an optional optimization update for ".NET 3&4" in the additional/optional update section of windows update, do not install this optional update, as for some reason it seems to break steam achievement manager, SAM is currently working for me again.

**Comment by MRxing11** [comment]
How can I contact you?

**Comment by MRxing11** [comment]
Can you give me your contact information?
