### ISSUE TITLE
Improve quality of images

### ISSUE THREAD

**Issue by Hexaae** [gibbed/SteamAchievementManager#356]
Minor thing... but can you improve quality of game image grids? They look like badly reduced from 32bit -> 8bit...
Not an important feature, but good looking would be even better ;)

P.S.
Thank you for this tool: was really useful after I moved some of my save games from different platforms (e.g. GOG -> Steam)

**Comment by gibbed** [comment]
Huh, I'm going to be honest, I don't remember deliberately setting it to 8-bit.
