### ISSUE TITLE
Launch a specific game in SAM.Game.exe

### ISSUE THREAD

**Issue by K14Mua** [gibbed/SteamAchievementManager#369]
Is there a way to launch the game with a specific Steam ID? Through a shortcut or cmd?

**Comment by gibbed** [comment]
Do you mean steam ID as in a user or an app/game?

If you mean app/game, you can create a shortcut to `SAM.Game.exe` with the appid as the command-line argument.

IE, for Team Fortress 2: `SAM.Game.exe 440`
