### ISSUE TITLE
Is it possible to modify the date when the achievement was unlocked? For example, change it to a past date like 10/01/2019?

### ISSUE THREAD

**Issue by cristoferluch** [gibbed/SteamAchievementManager#374]
For example, change it to a past date like 10/01/2019?

**Comment by gibbed** [comment]
No, the Steam API doesn't allow that.

**Comment by cristoferluch** [comment]
thanks

**Comment by cristoferluch** [comment]
Hello, 

I apologize for any inconvenience caused. Could you kindly consider removing this issue? 

Thank you for your attention.
