### ISSUE TITLE
How can i build for x64 steamclient64.dll?

### ISSUE THREAD

**Issue by NRTnarathip** [gibbed/SteamAchievementManager#377]
Hi😅, current now i'm try to use Lib with project "SAM.API" but it's not support on x64 build
so how can i integrate to my Project and my mod game is use steamclient64.dll
thanks

**Comment by gibbed** [comment]
You would be better served using something like [Steamworks.NET](https://github.com/rlabrecque/Steamworks.NET) than attempting to use SAM.API.

**Comment by NRTnarathip** [comment]
thanks you bro, it's work 👍👍
