### ISSUE TITLE
None of my Steam games load.

### ISSUE THREAD

**Issue by Wario3493** [gibbed/SteamAchievementManager#378]
I have been trying to unlock some achievements recently and it doesn't work. When I try to load up a game to unlock achievements, nothing loads! I've tried this on ALL my steam games.
<img width="482" alt="21211" src="https://github.com/gibbed/SteamAchievementManager/assets/130720837/74d0146d-f452-4cb7-b698-9bf18ae56e6f">

**Comment by LyraKush** [comment]
you need open your steam and don't stayed offline.

**Comment by kyroikoneko** [comment]
Same bug, black screen. Steam Online on.

**Comment by ach14624** [comment]
Temporary fix: open the game page (don't need to launch the game) in your Steam Library before opening it with SAM.
