### ISSUE TITLE
Game list in picker no longer supports searching by typing into the list control due to virtualization

### ISSUE THREAD

**Issue by monkeyef** [gibbed/SteamAchievementManager#39]
I remember in the older version 6.3, when i open SAM, I could type names to search for a game, but in the version 7.0, searching is not working for me. Does the new version still have this function?

**Comment by Itzamana** [comment]
Same problem. 7.0.6 can do this, but 7.0.10 and 7.0.11 can't.

**Comment by gibbed** [comment]
That's probably due to the virtualization of the list. I'll see if I can implement that again.

**Comment by darkl1ch** [comment]
i'm also really missing this feature :)

**Comment by CrafterKolyan** [comment]
+1

**Comment by FreePhoenix888** [comment]
Is there search bar right now? Do you mean bar on the top? I am unable to search right now
