### ISSUE TITLE
Achievements not loading

### ISSUE THREAD

**Issue by J-BrentfordFC** [gibbed/SteamAchievementManager#397]
As title says, I open a game and none of the achievements are loading.

![Screenshot 2024-07-17 063227](https://github.com/user-attachments/assets/aae31009-c80d-4b0a-872c-7823e2ecb0e7)

**Comment by tesisglep** [comment]
same happens to me
![image](https://github.com/user-attachments/assets/558baf02-6ff4-4709-a184-1ea9bb29f331)

**Comment by SinthAP** [comment]
Yeah, program is dead.

**Comment by mviny330** [comment]
![image](https://github.com/user-attachments/assets/4035484c-db39-4458-8625-0b89f0776c57)

**Comment by J-BrentfordFC** [comment]
I fixed mine

Don't know if this'll work for you guys but I was using the beta version of Steam so I went back to the non beta version and it started working again.

**Comment by ach14624** [comment]
Only a short term solution, once the update leaves Beta it might leave SAM completely unusable.

**Comment by ach14624** [comment]
Only a short term solution, once the update leaves Beta it might leave SAM completely unusable.

**Comment by xPaw** [comment]
If you open the game in the steam library first, does that fix it? Seems like the UserGameStatsSchema_{id}.bin file is not created.

**Comment by Triksus** [comment]
You just need to open the game,then refresh,it should display achievements now

**Comment by ach14624** [comment]
> If you open the game in the steam library first, does that fix it? Seems like the UserGameStatsSchema_{id}.bin file is not created.

Yes, this does fix the issue. Could this issue also be why the first achievement you unlock never get's synced online?

**Comment by gibbed** [comment]
Fixed by b3a66df0d1a870e1646a259698a670f6884fa7c9.
