### ISSUE TITLE
Achievements dont load

### ISSUE THREAD

**Issue by tesisglep** [gibbed/SteamAchievementManager#398]
I double click the game i want to unlock the ach and it doesnt show anything
![image](https://github.com/user-attachments/assets/31f1a44d-e195-416a-a47f-a7f8bc685622)

**Comment by mviny330** [comment]
![image](https://github.com/user-attachments/assets/0f323201-e5aa-4717-b077-e30f2b414524)

**Comment by enzaop** [comment]
me too

**Comment by HChengNuoH** [comment]
me too

**Comment by Kyochane** [comment]
![1](https://github.com/user-attachments/assets/371edbcb-2d13-4981-863f-410a9011a305)
![2](https://github.com/user-attachments/assets/36822e9e-fb71-4095-87b9-c1db1ee96233)
![3](https://github.com/user-attachments/assets/8bb8b85b-fa43-4074-bf90-eb62b8bf517d)
![4](https://github.com/user-attachments/assets/a4ddd89d-46e6-412b-be31-13ae3b55d08d)

For me it works.

**Comment by ach14624** [comment]
Temporary fix: open the game page (don't need to launch the game) in your Steam Library before opening it with SAM.

For this you don't need to leave the Beta (and also when the Beta becomes public release).

**Comment by lhwe** [comment]
This also may be an issue with steam in general, SAM won't always work for every game

**Comment by levelingCt** [comment]
> Solución temporal: abre la página del juego (no es necesario iniciar el juego) en tu biblioteca de Steam antes de abrirla con SAM.
> 
> Para esto no es necesario abandonar la Beta (y tampoco cuando la Beta se convierta en lanzamiento público).

gracias hermano me salvaste me funciono

**Comment by gibbed** [comment]
Fixed by b3a66df0d1a870e1646a259698a670f6884fa7c9.
