### ISSUE TITLE
Help me.

### ISSUE THREAD

**Issue by dubstepro9** [gibbed/SteamAchievementManager#40]
![default](https://user-images.githubusercontent.com/34993065/34465181-a504585e-eeb3-11e7-9bd5-a651b8f009cb.png)

**Comment by gibbed** [comment]
Does adding a game manually via ID work?

Are you able to access http://gib.me/sam/games.xml?

**Comment by dubstepro9** [comment]
Yes it works

**Comment by dubstepro9** [comment]
But so uncomfortable

**Comment by dubstepro9** [comment]
Program version 7.0.11
Before such was not

**Comment by gibbed** [comment]
Are you saying that 7.0.10 can get the games list properly?

**Comment by dubstepro9** [comment]
No I have tried all versions

**Comment by dubstepro9** [comment]
Not working still

**Comment by gibbed** [comment]
Okay, what version, if any, was it last working on?

**Comment by dubstepro9** [comment]
Help me...

**Comment by bmendonc** [comment]
I find that entering any random game id in, letting it launch, then after a few minutes, killing the process and restarting tends to refresh the list of games you have. That, or make sure that you are running the process with the same user you are running steam with.

**Comment by LarryFaulken** [comment]
What about delete the whole SAM folder and download it again？I fixed this
problem by this way
