### ISSUE TITLE
Archivements not showing in any game

### ISSUE THREAD

**Issue by ZavalaSebas** [gibbed/SteamAchievementManager#401]
![Captura de pantalla 2024-07-22 233717](https://github.com/user-attachments/assets/2f990943-70c3-4f1c-b038-a751ac437b65)

**Comment by TheOmegaShirou01** [comment]
I'm having the same issue

**Comment by ach14624** [comment]
Temporary fix: open the game page (don't need to launch the game) in your Steam Library before opening it with SAM.

**Comment by TheOmegaShirou01** [comment]
> Temporary fix: open the game page (don't need to launch the game) in your Steam Library before opening it with SAM.

This worked flawlessly. Thanks.....

**Comment by Sharpyku** [comment]
for me it's not working, i open the page steam game in library, then i open sam.exe and nohting happen, it's 0......

**Comment by testing61** [comment]
> Temporary fix: open the game page (don't need to launch the game) in your Steam Library before opening it with SAM.

thanks a lot bro!

**Comment by gibbed** [comment]
Fixed by b3a66df0d1a870e1646a259698a670f6884fa7c9.
