### ISSUE TITLE
Add 'Hide Completed' Option to Steam Achievement Manager

### ISSUE THREAD

**Issue by RIQUELMEEEEE** [gibbed/SteamAchievementManager#404]
Hi @gibbed,

I wanted to suggest a feature for SAM: a 'hide completed' option that would allow us to hide games that have already been 100% completed. This feature would make it easier to see which games still need achievements and help keep the list more organized.

**Comment by gibbed** [comment]
This should be implemented as of around 722475f539e24a1460a35fb22967d59d8ca7e602.

**Comment by gibbed** [comment]
Whoops, misunderstood the issue. This is desired for Picker, which isn't really possible with the Steam API as-is.
