### ISSUE TITLE
SAM picker doesnt work 

### ISSUE THREAD

**Issue by XsaidyX** [gibbed/SteamAchievementManager#407]
Hi, I have encountered such a problem, recently SAM PICKER has been working unstable, or does not work at all, when starting a game in which I want to hack achievements, I get the error "scheme loading error", I disassembled a lot, reinstalled, launched as administrator, but it does not help, tell me what To do? 
![image](https://github.com/user-attachments/assets/8fc11310-67ba-48c2-b139-7486524f1f38)

**Comment by testing61** [comment]
same error here

**Comment by XsaidyX** [comment]
> same error here

Try disabling the client's participation in beta testing, it helped me for a while (turn off on steam settings 
![image](https://github.com/user-attachments/assets/880d7129-cef7-4b4d-b50c-12f7ac31e7e9)

**Comment by Netshh** [comment]
> > same error here
> 
> Try disabling the client's participation in beta testing, it helped me for a while (turn off on steam settings ![image](https://private-user-images.githubusercontent.com/175149818/362257142-880d7129-cef7-4b4d-b50c-12f7ac31e7e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNzkxMTIsIm5iZiI6MTcyNTE3ODgxMiwicGF0aCI6Ii8xNzUxNDk4MTgvMzYyMjU3MTQyLTg4MGQ3MTI5LWNlZjctNGI0ZC1iNTBjLTEyZjdhYzMxZTdlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQwODIwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jY2U4NDdhMjk5YzVkYjlhYTVjZmEyMGNjYzA0Yzk0YWYzOTEwYTE3M2Y3OTJjNGVhOWQzMDVjM2ZmYzlkZjU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ay_QicpZGVmTiKK8mKYFxlPycbqlXWCfvEERjo7mNrY)

Thanks bro work for me after Turning of Beta Participation

**Comment by 0xE69** [comment]
Error is now there on the latest version.

**Comment by DeadStarlin** [comment]
And now Family Beta is no longer beta - so app is not working at all as it was...

**Comment by logicmoon** [comment]
Doesn't work anymore...

**Comment by thorvak** [comment]
Same issue without beta version since today

**Comment by H0t-5auc3** [comment]
same here, guess that's cuz of new family update

**Comment by levelingCt** [comment]
alguien sabe porque no funciona y si alguien sabe solucionar que ayude porfavor

**Comment by levelingCt** [comment]
> Lo mismo digo, supongo que es por la nueva actualización familiar.
a que te refieres con familiar ?

**Comment by J-BrentfordFC** [comment]
If its still not working try this:

Go to your steam library and find the game you want achievements on, click on it but dont launch it, then open the game on SAM and it should load

**Comment by DeadStarlin** [comment]
> If its still not working try this:
> 
> Go to your steam library and find the game you want achievements on, click on it but dont launch it, then open the game on SAM and it should load

It is just a workaround, not a fix... If your car brakes are broken, try to slow down with engine and then break with feet - same results - in longer term it is more annoying than helping

**Comment by DeadStarlin** [comment]
Fixed by [commit](https://github.com/gibbed/SteamAchievementManager/commit/b3a66df0d1a870e1646a259698a670f6884fa7c9)
