### ISSUE TITLE
probably a dumb question, but how the hell do I use this?

### ISSUE THREAD

**Issue by Dracu98** [gibbed/SteamAchievementManager#408]
I downloaded the three folders, opened each using speed commander and tried using both .exe-datas I could find. however, nothing happens.

this isn't so much an issue as much as it is me being absolutely overwhelmed and out of my depth here.

**Comment by lhwe** [comment]
I gotchu.

Step 1; Download the release ZIP file for your OS(usually Win64)
Step 2; Extract it, and run SAM.Picker.exe
Step 3; Select a game, for example Intoxicated Driver, just click I(or the starting letter of your game) until its selected and double click it
Step 4; Click the unlock button on the first tab to get all achievements
Step 5; Navigate to the 2nd page to set stats(is applicable)
Step 6; Press the "Commit Changes" button

Hope this helped! 😸

**Comment by Dracu98** [comment]
> I gotchu.
> 
> Step 1; Download the release ZIP file for your OS(usually Win64) Step 2; Extract it, and run SAM.Picker.exe Step 3; Select a game, for example Intoxicated Driver, just click I(or the starting letter of your game) until its selected and double click it Step 4; Click the unlock button on the first tab to get all achievements Step 5; Navigate to the 2nd page to set stats(is applicable) Step 6; Press the "Commit Changes" button
> 
> Hope this helped! 😸

it wooorked! thank you so much :D some achievements for borderlands 3 are bugged, so this is a genuine time saver
