### ISSUE TITLE
How to Use?

### ISSUE THREAD

**Issue by lmaowhatisthis** [gibbed/SteamAchievementManager#41]
I understand I sound dumb (I am not a big computer buff), but I have no idea how to use the files we download for the Achievement Manager from Gib. I have looked on the internet for any guides, but they all deal with the non-existing/removed website (gib.me/sam/). Can anyone follow me through the steps on how have the Manager to work?
Greatly appreciated.

**Comment by fbuireu** [comment]
You have to download the zip (or tar.gz, depending on your OS) from [here](https://github.com/gibbed/SteamAchievementManager/releases/tag/7.0.11), then unzip it and execute Steam and SAM.Picker (from the unzipped files).

Then a window will appear listing all your games in your profile, select them and unlock as achievements you wish.

P.S: you can only unlock those achievements that are not protected (server-side achievements, which are the most.

**Comment by lmaowhatisthis** [comment]
Thank you, I followed your steps and it worked perfectly. Much obliged
