### ISSUE TITLE
an error occurred while storing, aborting

### ISSUE THREAD

**Issue by imabduln** [gibbed/SteamAchievementManager#411]
I have been getting this issue recently, and I cant seem to use the application, and I have restarted my PC to see if it fixes anything, and it does nothing. I was only able to use a few times
![SAM Game_9eabV2xx68](https://github.com/user-attachments/assets/1728d2fc-f75d-4dde-9c52-351867750fdd)

**Comment by gibbed** [comment]
Fixed by b3a66df0d1a870e1646a259698a670f6884fa7c9.
