### ISSUE TITLE
Achievements not loading

### ISSUE THREAD

**Issue by RxgeVxn** [gibbed/SteamAchievementManager#413]
As soon as you click on any game that shows up on your steam achievement manager the dialogue box is just empty. No achievements loads and on the bottom it says that the game has no achievement at all

**Comment by nightmare-spirit** [comment]
same got any fix?

**Comment by RxgeVxn** [comment]
> same got any fix?

nope

**Comment by enzaop** [comment]
Same here

**Comment by 9564519** [comment]
Everything works for me...
Write more details about your situation. Attach screenshots and video recordings.
It is impossible to even try to solve what you described.

**Comment by TheGreenDragon** [comment]
Several titles are now greyed out on the main screen of the app. As below:
![image](https://github.com/user-attachments/assets/0d069ef5-73f2-4778-a1a2-a3a94bdbb935)

Choosing any application/game results in a "Failed to load schema" error at the bottom of the window. All achievements are blacked out and cannot be selected:

![image](https://github.com/user-attachments/assets/34c3f292-50e7-4675-8156-ff7065f50586)

App has been launched as standard user and admin both with same results.

**Comment by al3x067** [comment]
same for me

**Comment by PS67795** [comment]
Same here. The image shown above by @TheGreenDragon is what I am seeing on  SAM. Worked fine yesterday until I installed the newest Windows 11 update.

**Comment by probablyraging** [comment]
I am the dev behind [Steam Game Idler](https://github.com/probablyraging/steam-game-idler), a Steam utility tool with an achievement unlocker similar to SAM.

I have noticed that achievements are no longer able to be unlocked via the `Steamworks.NET.dll` _(Steamworks SDK wrapper)_, used by both SAM and SGI. I see an [update was made yesterday on the Steamworks blog](https://store.steampowered.com/news/group/4145017), but no mention of changes to the SDK or API endpoints. Maybe just a coindedence in timing. But achievements are still able to be unlocked via actually playing the game, and posibly via other method/libraries.

There was also a [Steam Client update](https://store.steampowered.com/news/app/593110/view/4599952112537386540) a few days ago which might be a potential cause of the issue.

I'm still investigating the issue myself, and will post an update here if I can figure out a fix. If any maintainers of this repo could do the same, that would be awesome.

Thanks

**Comment by gibbed** [comment]
SAM does not use `Steamworks.NET.dll`, it uses its own distinct implementation of `steam_api.dll` separate from any other implementation.

I haven't had the time to look into this in depth, as far as I know, achievement managing via the Steamworks API is working fine. This is purely an issue with Steam no longer writing the relevant schema files with information about game achievements to the expected location when the Steamworks API is initialized as was the previous behavior.

**Comment by probablyraging** [comment]
> SAM does not use Steamworks.NET.dll, it uses its own distinct implementation of steam_api.dll separate from any other implementation.

Yeah my bad, not sure why I thought it did.

SGI wasn't having issues with fetching game schema as it was doing so via the web API without issue, but we were definitely having an issue with modifying achievements/stats via Steamworks, which I thought likely had something to do with this issue, now I'm thinking probably not.

**Comment by gibbed** [comment]
> This is purely an issue with Steam no longer writing the relevant schema files with information about game achievements to the expected location when the Steamworks API is initialized as was the previous behavior.

I updated to the most recent Steam client and checked, Steam is still writing the schema files but SAM might be trying to load them too quickly, seems like Steam might not flush the schema to disk before the `UserStatsReceived` callback is sent.

**Comment by probablyraging** [comment]
Yeah, so I am definitely noticing some correlation between this issue and my own.

`UserStatsReceived_t` seems to give an `k_EResultOK` in all cases, but further calls such as `GetAchievement` or `SetAchievement` all seem to fail, but not for all games. For example, there is no issue with Warframe or Apex Legends, even SAM loads the schema for these without an issue.

**Comment by probablyraging** [comment]
Weirdly enough, this users comment is a workaround. After veiwing the game in your library, SAM will load the game's achievements without an issue.

> If its still not working try this:
> 
> Go to your steam library and find the game you want achievements on, click on it but dont launch it, then open the game on SAM and it should load
> 
> _Originally posted by @J-BrentfordFC in https://github.com/gibbed/SteamAchievementManager/issues/407#issuecomment-2348068034_

**Comment by gibbed** [comment]
It looks like Steam has deprecated `RequestCurrentStats`; a call to `RequestUserStats` seems to be causing Steam to write a schema before firing the `UserStatsReceived` callback.

**Comment by gibbed** [comment]
Fixed by b3a66df0d1a870e1646a259698a670f6884fa7c9.
