### ISSUE TITLE
Icons contrib

### ISSUE THREAD

**Issue by Hexaae** [gibbed/SteamAchievementManager#414]
A pair of icons for this project, free and AI generated for SAM.Game.exe and SAM.Picker.exe

![image](https://github.com/user-attachments/assets/f66374da-2132-44dd-8bf6-1820fa3ca1e8)

[icons.zip](https://github.com/user-attachments/files/17007440/icons.zip)

**Comment by gibbed** [comment]
I appreciate the desire to contribute, but I currently have no interest in updating the icons.

Additionally, I won't accept AI-generated submissions. That's a whole other thing, especially legally.

**Comment by Hexaae** [comment]
No prob. Good I didn't spend much time creating them from scratch this time... 😉
