### ISSUE TITLE
sam detects 53k games even tho i have 40 in my library help??

### ISSUE THREAD

**Issue by zImMateja** [gibbed/SteamAchievementManager#416]
![image_2024-09-16_051235411](https://github.com/user-attachments/assets/70b9bcf0-e2da-4010-bd55-50bfa02c1e57)

**Comment by gibbed** [comment]
That would be every game SAM checks for, so something is wrong or unexpected with your Steam client if it's saying you own all of them (unless you actually own all of them).

Have you changed anything in your Steam settings that is out of the ordinary? Are you using Family Share, etc?

**Comment by zImMateja** [comment]
> That would be every game SAM checks for, so something is wrong or unexpected with your Steam client if it's saying you own all of them (unless you actually own all of them).
> 
> Have you changed anything in your Steam settings that is out of the ordinary? Are you using Family Share, etc?

i dont recall editing steam settings,is there any specific settings i should look for to see what they are or?

**Comment by gibbed** [comment]
The only thing I can think of that would affect ownership checks within Steam itself is Family Share. Are you using any third party software that modifies Steam in some way?

**Comment by zImMateja** [comment]
> The only thing I can think of that would affect ownership checks within Steam itself is Family Share. Are you using any third party software that modifies Steam in some way?

ohh might be koalageddon a dlc unlocker,im not in a family share,it works if i add a game manually and it detects that i dont have the game for example dying light 2 but on a game i have it works
![Uploading image_2024-09-16_052713130.png…]()

**Comment by gibbed** [comment]
Please disable anything like that software prior to using SAM. SAM uses Steamworks APIs to determine if you own a game to build its list of games.

**Comment by zImMateja** [comment]
yep,fixed it all i had to do was uninstall koladageddon intergrations and it lists my game normally now
![image](https://github.com/user-attachments/assets/42a44bbd-f3ab-45a6-a9d9-17dfbb272d5c)
