### ISSUE TITLE
Achievements not displaying when opening games

### ISSUE THREAD

**Issue by LazaroVR** [gibbed/SteamAchievementManager#419]
I’m experiencing a problem where achievements do not appear when opening games.

![image](https://github.com/user-attachments/assets/cebc6d2c-bd41-4708-82ba-7e43620e0fa1)

The app opens fine, and the games are displayed correctly. However, when I select a game, no achievements show up for me to add or remove. This has been happening for a few days now. Yesterday, some games were still working intermittently, but today none of the games opened properly.

It might be related to a recent update compatibility issue, but I'm not sure.

**Comment by kostaskiller** [comment]
you have to change steam interface.
go:
steam app > settings > interface > client beta participation (change from steam beta update to no beta chosen)
then run steam archivements with admin rights.

**Comment by kostaskiller** [comment]
yes!! i try this old solution and works fine for me!

**Comment by gibbed** [comment]
If the beta client is what is causing the issue, then you will need to revert for usage with SAM. I'm not interested in chasing fixes for the beta client.

**Comment by LazaroVR** [comment]
I managed to resolve the issue by updating to version 7.0.37. Interestingly, I noticed that this version had been available a couple of days before my problem occurred, but when I searched for it, I could only find version 7.0.25. For anyone facing the same issue, here’s the link to the updated version:
[github.com/gibbed/SteamAchievementManager/releases/tag/7.0.37](https://github.com/gibbed/SteamAchievementManager/releases/tag/7.0.37)
