### ISSUE TITLE
SkyrimSSE: Progressive Unlock of Achievements?

### ISSUE THREAD

**Issue by lmstearn** [gibbed/SteamAchievementManager#42]
The idea is based on an alternative to what XShadowman has [already done](https://www.nexusmods.com/skyrimspecialedition/mods/3619/?tab=description), however the way it's set up for users may not be [agreeable to everyone](https://steamcommunity.com/app/489830/discussions/0/224446614459510687/).
Let's suppose we load up a SKSE64 based plugin that reads game data which is interpreted as being eligible for achievements. We then, with the assistance of SAM methods, and, with a modded game, are able to view a progressive tally of achievements on Steam like it was back in Oldrim.
A super easy way is for the SKSE64 based plugin to simply dump the relevant data to a csv or similar, and for SAM to update the results on next run. Or we can use something like a SAM dll plugin also configured via the integrated SSE plugin in the game [MCM menu](https://github.com/schlangster/skyui/wiki/MCM-API-Reference). The second method would be less intrusive, and more user friendly.
Absolutely convinced this method of achievement_control is on par- or better than the above-mentioned alternative.
Thoughts?

**Comment by gibbed** [comment]
This seems excessive to bring SAM into the picture for this, doesn't Skyrim already pull in Steamworks API? Then you have access to its achievement APIs already.

**Comment by lmstearn** [comment]
I see, Not being experienced in SteamAPIs, a cursory glance only reveals [read only methods for achievements](https://developer.valvesoftware.com/wiki/Steam_Web_API#GetPlayerAchievements_.28v0001.29). Thus the reason for the question here. Else it's decompiling the SSE exe, which was not originally an option.
But if you're not interested, best to part company at this stage.
Thanks for the quick response.

**Comment by gibbed** [comment]
That's the web API for Steam. Steamworks is an API that Skyrim most certainly uses (cloud saves, achievements, etc).

It's more that this is out of scope for SAM than anything.

**Comment by gibbed** [comment]
And on second though, IIRC, there are "AddAchievement" and "ClearAchievement" functions as part of Skyrim's scripting language. That should still be a thing in the SE.

**Comment by lmstearn** [comment]
@Gibbed: Appreciate the advice. :)
