### ISSUE TITLE
Many games are showing blank achievment lists

### ISSUE THREAD

**Issue by Oxfordss** [gibbed/SteamAchievementManager#423]
A lot of games that once showed me all the achievements to activate are now showing nothing. This only started within the last month. Some games are like this and some aren't.
![Screenshot (652)](https://github.com/user-attachments/assets/67b68603-8b92-41f4-ab55-72fe375a048b)

**Comment by Marcus101RR** [comment]
Same Issue here, and not fixed, Every game I start seems to be empty.

**Comment by etrernal** [comment]
Press the Refresh button and it should work.

**Comment by Oxfordss** [comment]
Ok, so I restarted PC and reinstalled the manager and it now works. Guess I wasn't up to date on the latest version.

**Comment by Jagailo** [comment]
Works with VPN of the region where this game is still sold
