### ISSUE TITLE
Irregularly Working Properly

### ISSUE THREAD

**Issue by Marcus101RR** [gibbed/SteamAchievementManager#425]
Date: October 1st, 2024

Ever since the new Family Sharing system was added this has no longer been working properly as expected. I own games that work and show up, I own games that don't work and don't show up. I have friend's games that work, and friend's games that don't work. It is a complete Chaos, so I'll take each case and post it.

FORSPOKEN CASE - Legally Own - Works
![Screenshot 2024-10-11 191245](https://github.com/user-attachments/assets/79a65c2c-8486-445e-b436-1a898815c577)
![Screenshot 2024-10-11 191340](https://github.com/user-attachments/assets/9dc24685-4443-4b52-ba69-cf3e02157aa9)

Dragon Ball Sparking ZERO! CASE - Legally Own - Doesn't Work
![Screenshot 2024-10-11 191525](https://github.com/user-attachments/assets/b866ac43-29b1-45ad-8b6e-a62bf175b8ff)

FORWARNED CASE - Don't Legally Own (Friend) - Doesn't Work
![Screenshot 2024-10-11 191640](https://github.com/user-attachments/assets/c74b0a74-faca-4fd4-9cd9-49a4efceeaf6)

This is just an example of some of things, there are a few that do work but why they work and what makes them work is baffeling at the slightest, No system changes have been made. I have updated Windows to the latest update recently though I doubt that could be the issue.

The most baffeling is that games I actually own sometimes don't even have a Banner image, as if I don't even own the game? Yeah ok, whatever you say. I own them, if non legit games worked before I see no reason why legal games atleast should work. I use this to find hidden achievements that tell you the description on how to unlock them, since this was my way of finding out.

**Comment by gibbed** [comment]
Your screenshots show that you are not using the latest version of SAM.

**Comment by Marcus101RR** [comment]
Not sure how you can tell that I am or am not, but if you are refering to Steam Achievement Manager 7.0 at the top of the window bar. I think you should be aware that no matter which release I download from your list, it always displays this, you may want to considering fixing that in your compile code to display the full version number. I can assure you I am using 7.0.37

**Comment by gibbed** [comment]
Your screenshots do not show the more recent UI changes in SAM.

**Comment by Marcus101RR** [comment]
Restarted My Computer, not it actually seems to work. Fixed / Issue Not a Bug
