### ISSUE TITLE
Achievements and Stats do not show up! 

### ISSUE THREAD

**Issue by 0Canee** [gibbed/SteamAchievementManager#426]
![imagem_2024-10-11_212718955](https://github.com/user-attachments/assets/49fd6859-2260-46d7-ab32-bd878c604201)

**Comment by 0Canee** [comment]
@gibbed This happened to me around 2 days ago, I already tried turning off my computer and turning it back on, restarted steam, but nothin works, is there any way you can help me here?

**Comment by gibbed** [comment]
Your screenshots suggest you are not using the latest version of SAM.

**Comment by 0Canee** [comment]
> Your screenshots suggest you are not using the latest version of SAM.

True, I updated it and now it's working, sorry for the confusion lols. Have a nice day!
