### ISSUE TITLE
Cannot find my game Hades2

### ISSUE THREAD

**Issue by doomsdayer** [gibbed/SteamAchievementManager#427]
My game Hades2 can't be identified in SAM's list. 
![image](https://github.com/user-attachments/assets/a17ae461-d832-49b5-819a-e39165d303f7)
![image](https://github.com/user-attachments/assets/129028ad-c99f-46ee-b723-e46a8c0fa148)
 
If I added the game by the id 1145350
It still can't read my achievements.
![image](https://github.com/user-attachments/assets/b04e3d03-2c72-41e4-ac14-7017603eb948)

**Comment by gibbed** [comment]
Hades II does not have any achievements/stats on Steam. That may change in the future, but until then it's unsupported in SAM.
