### ISSUE TITLE
red orchestra 2 multiplayer

### ISSUE THREAD

**Issue by leroywatson** [gibbed/SteamAchievementManager#43]
just leaving this here to let you know that most of red orchestra 2 multiplayer achievemetns are locked in sam..:c

**Comment by gibbed** [comment]
I have no interested in trying to bypass these protections, it's out of scope for SAM.

**Comment by philpodolski** [comment]
Is there any way to reset literally 1-2 achievements in Rising Storm 2 I don't like they look like?
I know only about reset stats including all the achievements. But I woudn't like this way, cause I've got rare achievement.

**Comment by gibbed** [comment]
That would be the only way, I'm afraid.
