### ISSUE TITLE
doesn't work for arma 3 

### ISSUE THREAD

**Issue by kitahero** [gibbed/SteamAchievementManager#430]
i once use this unlocked all achievements of arma 3, but the achievements will be unlocked again as i try to relock them with the time when i did the relock action

**Comment by theFish2171** [comment]
I really hope I have never started arma 3 so I didn't have to deal with it's achievements

The only way (I've managed) to remove arma 3 achievements is by nuking the game, hitting the `💣reset` button on the top, and then unlock the achievements you want or need

**Comment by kitahero** [comment]
It works!!!!
thanks bro
