### ISSUE TITLE
SAM claims I don't own a game ... but I do and here is proof!

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [gibbed/SteamAchievementManager#44]
![2018-01-09 07_29_16-](https://user-images.githubusercontent.com/10351221/34723137-1192a640-f50f-11e7-9dda-17a4e47c8822.png)

**Comment by P3rf3ctXZer0** [comment]
I used a super save back in the day but now I cannot undo my sin. I have all the DLC and if you aren't familiar with Afterbirth + basically its a mod tool for Issac Afterbirth that was also DLC. Anyways when it was first released you could not make progress in the game while using mod even if the mods were cosmetic only and now I am unable to legitly regain the achievements ... and it saddens me. I only used the save so I could enjoy everything after birth plus had to offer :(

**Comment by gibbed** [comment]
It's not so much about proof, is that the Steam API that SAM uses says you don't own the game, and thus, cannot interact with it via the API.

**Comment by P3rf3ctXZer0** [comment]
Well I do I got it the day I came out I play daily so wtf.

**Comment by cristinacke28** [comment]
I think you try to open a game with the wrong appID in SAM, but that is unlikely.
Anyway try 250900
