### ISSUE TITLE
Time spent in the game

### ISSUE THREAD

**Issue by Hadozz** [gibbed/SteamAchievementManager#443]
Could you add a time that would show how much time I spent in the game during the current session? Sometimes I use SAM to accumulate hours, and this feature would be very useful.

_I understand that the project is open source, but I don't know how to program_

**Comment by gibbed** [comment]
Out of scope for SAM. If you want to idle games there are better tools for that.

**Comment by gibbed** [comment]
https://github.com/probablyraging/steam-game-idler
https://github.com/JustArchiNET/ArchiSteamFarm
