### ISSUE TITLE
Activated Achievements Not Displaying in 'Perfectionist' and 'Achievement Count

### ISSUE THREAD

**Issue by DutraGames** [gibbed/SteamAchievementManager#448]
I encountered an issue where activating achievements for a game does not update their display in the Perfectionist and Achievement Count sections. Additionally, the "perfect game" status is not shown in these sections. However, the game still appears correctly listed under Games > Perfect Games.

Below are images to illustrate the issue:

![Screenshot_20241125_110023_Steam.jpg](https://github.com/user-attachments/assets/51f3f92e-909d-48d5-b548-f2eb9d06c501)

![Screenshot_20241125_110038_Steam.jpg](https://github.com/user-attachments/assets/3a361d09-97d6-4435-b63d-e2870e3b461c)

This inconsistency makes it difficult to track and manage achievements. Could this be reviewed to ensure activated achievements and perfect game status are displayed consistently across all sections?

If needed, I can provide more details or additional examples.

**Comment by gibbed** [comment]
This sounds like a problem on Steam's end, not much SAM can do about that.

**Comment by DutraGames** [comment]
> This sounds like a problem on Steam's end, not much SAM can do about that.

I'll run some tests by activating achievements with a longer time gap between them to observe the behavior. This might help determine if the issue is related to timing or how the achievements are being processed by the system. Once I have results, I'll share them here.

**Comment by DutraGames** [comment]
I’ll be closing this issue because, after testing with a game using a longer time gap, I observed mixed results: the system did not work perfectly when I used a game that was already platinum. However, when testing with a game that had no achievements unlocked, the system worked as expected.

If anyone encounters similar issues, feel free to reopen the issue with more details.
