### ISSUE TITLE
Server-side achievements

### ISSUE THREAD

**Issue by fbuireu** [gibbed/SteamAchievementManager#45]
Hi!

I know that SAM does not bypass and does not reach server-side achievements but do you know any other tool to unlock them?

Thanks

**Comment by Suvitruf** [comment]
It's not possible by design.

**Comment by ScienceDiscoverer** [comment]
Is it possible to do this if you somehow could host your own dedicated game server and then pull some strings to unlock achievements?

**Comment by Suvitruf** [comment]
> 
> 
> Is it possible to do this if you somehow could host your own dedicated game server and then pull some strings to unlock achievements?

AFAIK, not. You have to add severs IPs into whitelist in dev dashboard. Even if you are able to run server locally, Steam will reject those requests.
So, if you don't have access to dev dashboard, you couldn't do that.
