### ISSUE TITLE
"Retrieving stat information..."

### ISSUE THREAD

**Issue by XerM** [gibbed/SteamAchievementManager#46]
I tried loading multiple games and none of them seem to bring up any achievements. It'll just stay blank after I pick a game and just say "Retrieving stat information..." Is this version of SAM not updated or is there something I'm missing? 
Tried running as admin with both SAM Game.exe and SAM Picker.exe, tried deleting and re downloading the latest version, tried troubleshooting it, I even tried waiting an hour to see if it was because it was just slow for some reason but still nothing.

**Comment by XerM** [comment]
Didn't try fixing steam itself, I uninstalled it and reinstalled it and now it's loading the achievements. Sorry :x!

**Comment by gibbed** [comment]
It's fine, glad you got it sorted.
