### ISSUE TITLE
 Blocked Achivements

### ISSUE THREAD

**Issue by Vampire94937** [gibbed/SteamAchievementManager#48]
What does it mean when an achievement is "protected" and I can't access it...
I thought this was made to unlock achievements, how am I supposed to do that if I can't even connect to the damn things?

**Comment by gibbed** [comment]
Protected achievements are ones that can only be unlocked from a game server or a whitelisted game server. Thus, SAM cannot touch them (and I have no intentions of trying to get around it).

**Comment by philpodolski** [comment]
What about resetting protected achievement/s, not unlocking?

**Comment by gibbed** [comment]
You might be able to get away with that by resetting all achievement/stats state. You won't be able to directly interact with the achievements though.
