### ISSUE TITLE
Project Genom

### ISSUE THREAD

**Issue by Osryder** [gibbed/SteamAchievementManager#49]
Do not remove statistics or achievements from the game.

**Comment by gibbed** [comment]
What?

**Comment by Osryder** [comment]
SAM does not work for the successes and stats of the game "project genom"

**Comment by gibbed** [comment]
Okay.

Why? I need more information than "it doesn't work".

**Comment by Osryder** [comment]
For statistics, SAM does not delete them, can not be reset.
The successes are removed but they reappear after a few seconds.

**Comment by gibbed** [comment]
Stats marked as "Increment Only" can only be increased, not reset or reduced individually.
