### ISSUE TITLE
Games' name Mojibake

### ISSUE THREAD

**Issue by HMBSbige** [gibbed/SteamAchievementManager#5]
A flaw caused by Windows code pages.

Some Games' name contain unicode characters can not display correctly in Listview.

For example, any game's name contain```™```, and game appId [384190](http://store.steampowered.com/app/384190/)
![](https://user-images.githubusercontent.com/19153265/32786957-4fea7d5a-c990-11e7-8978-c1d83eefa412.png)

↑Different code pages show different.

My Windows code page is 936.I [fix](https://github.com/HMBSbige/SteamAchievementManager/commit/7039563546695c7b0317c6aa3e6a2e708deee1df#diff-fc3e8808df6b82bd96bd226ba4bd7ffbL52) this temporarily, but it can still lose some unicode chars because of encoding.

I think maybe it can directly display unicode.

**Comment by gibbed** [comment]
I have a more proper fix for this planned, but yeah, it's been a known issue for awhile.
