### ISSUE TITLE
Question about the Flags i.e Increment Only or UnknownPermssionsFlags etc.

### ISSUE THREAD

**Issue by gaveitatry** [gibbed/SteamAchievementManager#51]
Can you explain what IncrementOnly and UnknownPermissionFlags and what any other 'Extra' flags are and what they do or mean?

The reason that I ask is that there is a particular IncrementOnly that seems to only let me change the value in small amounts, like less than 30.  And there is one UnknownPermissionFlags that won't ever let me change the value at all.

If you could provide more information on these flags, it would put me at ease being able to understand it better and what limits there are and if there is anything that I can or cannot do about them.

Thank you in advance.

**Comment by cristinacke28** [comment]
Stats marked as "Increment Only" can only be increased, not reset or reduced individually.
