### ISSUE TITLE
Missing achievements in Payday 2

### ISSUE THREAD

**Issue by jakey1995abc** [gibbed/SteamAchievementManager#55]
Payday 2 is missing many achievements in SAM. I've never noticed any issue like this during the many years of me using this tool. I am using the latest version (7.0.11) of SAM and latest beta version (15119863247 from feb 28 2018) of Steam.

**Comment by gibbed** [comment]
SAM uses the cached achievements information from Steam to load information about available achievements.

You can try the following:
1. Exit Steam.
2. Delete/move the directory `<STEAM PATCH>\usercache\stats`.
3. Start Steam.
4. Start Payday 2.
5. Exit Payday 2.

This should force it to recache the stats data for Payday 2.
