### ISSUE TITLE
Games I don't own are listed

### ISSUE THREAD

**Issue by vankasteelj** [gibbed/SteamAchievementManager#56]
Hi, SAM lists some games I do not own in the list. Here are the ones I identified on my list, it might be missing some: 
- DC Universe Online
- Empires
- Eternal Silence
- PC Gamer (this looks more like a curator?)
- Source Filmmaker (a software?)
- Unreal Developmen Kit (another software?)

**Comment by crixusdeux** [comment]
Because SAM displaying a list of games, not your library.
If you need to find a game what is not listed, add steam id in search field and press Add game.

**Comment by vankasteelj** [comment]
Sorry, but your comment doesnt seem to make sense to me: 99% of the games listed by SAM are games I own (and I do not own 99% of what Steam has). Hence I figured: "hey, it's pulling a list of my games", but then, again, also some that I do not own.

**Comment by gibbed** [comment]
There's no built-in functionality in the Steam API that lets you iterate the games you own. What happens is on startup, the picker downloads a list of games that have achievements from my server. Then the picker checks every game via the Steam API in this list if Steam considers it a game you own.

A few of the games you've listed are free titles, like PC Gamer. Though PC Gamer has been delisted from the Steam store. You can probably still install it: steam://install/92500
