### ISSUE TITLE
Creating a Shortcut for Opening a Specific Game

### ISSUE THREAD

**Issue by gaveitatry** [gibbed/SteamAchievementManager#57]
Question #01

What is the difference between the SAM.Picker and SAM.Game exe's?  Both are exe's.  Both are the same size 44 KB.  And both seem to open the same exact program.

Question #02

Is there a way to create a Shortcut that opens a specific game within S.A.M?

For example, something like this:
"C:\Users\gaveitatry\Programs\Steam (S.A.M) 6.3\SAM.Picker.exe" SAM.Picker://open/SAM.Game/app/{gameappnumber}

or something like that?

**Comment by gibbed** [comment]
Picker is the application that lets you select a game.
Game is the application that lets you manage achievements.

Game will start Picker if it is started without any application ID passed to it on the command-line.

If you want to open a specific game/app every time, create a shortcut to SAM.Game.exe with the appID of that game/app.

eg:

`SAM.Game.exe 440` would open Team Fortress 2.

**Comment by gaveitatry** [comment]
Thank you.
