### ISSUE TITLE
Says Steam isnt Running, when it is!

### ISSUE THREAD

**Issue by Gchild40** [gibbed/SteamAchievementManager#59]
so yea im using linux and running sam.game.exe and it says Steam isnt running even though i have steam open!  can somebody help me please!

**Comment by gibbed** [comment]
SAM isn't intended to function on Linux. You _may_ be able to get it working using WINE via using https://github.com/xomachine/SteamForwarder but I haven't tried myself or heard any results from anyone who has tried it.
