### ISSUE TITLE
sam v7.0.11 - letter/name -> navigation jump

### ISSUE THREAD

**Issue by darkl1ch** [gibbed/SteamAchievementManager#60]
hello,
just updated to v7.0.11 from version 6.3* and i realized that the jump to game is not working.
in 6.3* when you started to write the game's name or even just a letter, the select/highlight jumped to the first match started with the letter.
so: when you start the program, it shows the games in alphabetic order and if you hit "w" for example, it goes down to the games which starts with letter "w".

this feature is not working in the new version, but it was pretty good to use.

**Comment by Ash258** [comment]
Duplicate of #39

**Comment by darkl1ch** [comment]
right. sorry, didn't see :)
