### ISSUE TITLE
Is It Normal?

### ISSUE THREAD

**Issue by zhz1237ok** [gibbed/SteamAchievementManager#68]
![snipaste_2018-05-19_09-17-33](https://user-images.githubusercontent.com/38283893/40263591-31691942-5b47-11e8-8130-78dc2d69c099.png)

**Comment by zhz1237ok** [comment]
a few game cant open the unlock screen (i was using gotkrypto76's version's "Unlock All" function)

**Comment by gibbed** [comment]
This means SAM wasn't able to access the Steam API. This either means your Steam is running as a different user or it's not running. Supposedly rebooting helps resolve this problem as well if it persists.
