### ISSUE TITLE
Linux version.

### ISSUE THREAD

**Issue by WaffenAntrix** [gibbed/SteamAchievementManager#69]
Will there be a version on Linux?

**Comment by VinLark** [comment]
If you just want to Idle, use steam-idle. If you actually want to hack achievements, use a virtual machine

**Comment by gibbed** [comment]
No plans for a Linux version currently, that would likely require an overhaul of SAM.API that wouldn't happen any time soon. You _may_ be able to get away with using https://github.com/xomachine/SteamForwarder with a combination of SAM and WINE.
