### ISSUE TITLE
not unlocking any achievement

### ISSUE THREAD

**Issue by MVXIII** [gibbed/SteamAchievementManager#7]
I dont know what's wrong, the software run just fine. ticking on the achievement doesnt do anything for me

**Comment by gibbed** [comment]
You need to click the Store button in the top right (it has an icon that like a radio tower) to commit any changes made.

**Comment by MVXIII** [comment]
It works now, thank you so much.

**Comment by gibbed** [comment]
I pushed a new commit to make that button more obvious. It's definitely unclear language in the UI that's been mentioned in the past by others.
