### ISSUE TITLE
OnDownloadList runs on main thread

### ISSUE THREAD

**Issue by xPaw** [gibbed/SteamAchievementManager#70]
Which causes the entire UI to free while its processing.

I identified 3 separate things that are slow enough to block:

- Steam API calls (get name and logo)
- `_Games.Any()` calls while adding games
- Final winforms game list refresh

**Comment by gibbed** [comment]
Note for self: `BackgroundWorker`.`RunWorkerCompleted` actually runs in UI thread, I am good at reading documentation. :no_mouth:

**Comment by gibbed** [comment]
Fixed with #73.
