### ISSUE TITLE
Norton deletes the files

### ISSUE THREAD

**Issue by TheIntelloBox** [gibbed/SteamAchievementManager#72]
Hi,

Norton detects a virus. :(

**Comment by Hampusm** [comment]
https://www.lifewire.com/exclude-files-from-norton-antivirus-scans-153348

**Comment by gibbed** [comment]
Yeah this isn't an issue with SAM (or at least, there's nothing I can really do about it). Exclude the files from Norton if it's blocking you from using SAM.
