### ISSUE TITLE
Sam is not working

### ISSUE THREAD

**Issue by Xedon420** [gibbed/SteamAchievementManager#81]
Hi,

I can't use the app, because every time I startup the app or open a game archive it causes a logout of steam. That means when I select a game in SAM Picker I have to login in Steam again. Even after re-login that same game. 

Any ideas or solutions?

OS: Windows 10 x64
SAM version: 7.0.16

**Comment by Xedon420** [comment]
I fixed this Issue with a reinstall of steam.

**Comment by gibbed** [comment]
Great, for the record, SAM should never be the origin of these issues. If it caused something like this, other games using the API would also do so.
