### ISSUE TITLE
Steam Achievement Manager and VAC Ban

### ISSUE THREAD

**Issue by SNOWDOG947** [gibbed/SteamAchievementManager#82]
After using SAM myself for over a dozen games on Steam I have been very impressed by how easy it was to use and get all the achievements desired in just a few clicks. I would recommend this to anybody if it wasn't much of a cheat, although I'm not too sure about about whether it is a cheat or not but several people believe it to be so which makes sense because you don't work hard for the achievements yourself although some people do put countless hours grinding as much achievements as possible and thus should be able to use something like this as some achievements are no longer possible to achieve.

My question on this is if anybody knows whether or not this can get you VAC banned any time soon. Currently I have been lucky enough to not get VAC banned and I even messaged one of the Valve Staff members asking if this could potentially get me banned. To my relief the staff member said that this will not get me banned as only Cheats that give players an advantage over other players will trigger VAC bans but apparently it is not appreciated by Valve and they guided me on how to reset my achievements which I later did to please them and so that nobody will report me for suspected cheating/hacking, hopefully. 

Finally, I attached a picture to this post so that you guys can read the reply for yourself and tell me what you guys think and I hope that you guys can give me your honest answers. One of my friends told me that "SAM only interacts with the Steam Client and VAC is run by the game process" (whatever that means) so if somebody could please evaluate this for me I would greatly appreciate it so that several others that are having this same question and myself can be at peace again knowing that our beloved accounts will not be banned any time soon.

To conclude, the Staff member told me to contact the developer of the SAM application for assistance and further clarification so if whoever created SAM could please take a look at this post or if somebody could inform me on how to contact the developer directly I would be grateful. Also, I would appreciate it if your replies could be as neatly typed and detailed as possible with reliable quotes and/or screenshots from your resources. (Please let me know if there is anything that I need to clarify or build on) Thanks in advance! 

Sincerely,
SNOWDOG947

https://user-images.githubusercontent.com/40772867/42182630-bdf51b4e-7df3-11e8-9183-d19f8d7a02a1.PNG

**Comment by gibbed** [comment]
I've never heard of anyone getting VAC banned due to SAM. The best thing to do is to never run SAM at the same time as any VAC-enabled game, and you should be fine.

**Comment by amayra** [comment]
how did they tell you to reset your achievements ?
