### ISSUE TITLE
Use HTTPS for media instead of HTTP.

### ISSUE THREAD

**Issue by Itzamana** [gibbed/SteamAchievementManager#87]
Looks like the GFW is blocking "http://media.steamcommunity.com". 
Changing it to "https://media.steamcommunity.com" should be able to solve the problem.

Thanks for this useful tools!

**Comment by gibbed** [comment]
What's "GFW" in this context? It's working fine here.

**Comment by Itzamana** [comment]
GFW: https://en.wikipedia.org/wiki/Great_Firewall
In China, we can't open "http://steamcommunity.com" without a VPN.
The best we can do is add "steamcommunity.com" in hosts and keep use "https://steamcommunity.com".

**Comment by Itzamana** [comment]
I don't know if that I said clearly. I'm sorry for my poor English… :>
