### ISSUE TITLE
I can't see the list of achievements?

### ISSUE THREAD

**Issue by WusGucciMayn** [gibbed/SteamAchievementManager#89]
I see all my games but I can't see any of the achievements for the games!?

**Comment by Ash258** [comment]
Which game? Could you attach screenshot?

**Comment by WusGucciMayn** [comment]
Every game I've tried so far. I can see all my games but when I select a game no achievements are visible. I can't upload a screenshot right now since I'm not on my personal pc. Will upload when I get home.

**Comment by WusGucciMayn** [comment]
I just got home and for some reason the achievements are showing again...
