### ISSUE TITLE
I cant clear recent activity on Steam

### ISSUE THREAD

**Issue by 01D00M** [gibbed/SteamAchievementManager#9]
There used to be 4 different boxes on sam picker in russian which you would click to clear recent activity. Today when i tried to clear recent activity the boxes werent there

**Comment by gibbed** [comment]
[I commented on this in another issue](https://github.com/gibbed/SteamAchievementManager/issues/3#issuecomment-346905206).

If you want to, you can create shortcuts to SAM.Game.exe with the appids of those apps that clear your activity.

**Comment by 01D00M** [comment]
Thank you :D
