### ISSUE TITLE
Steam is not running while Steam is running in Wine

### ISSUE THREAD

**Issue by nikitastepan0v** [gibbed/SteamAchievementManager#92]
![screenshot_20181012_192901](https://user-images.githubusercontent.com/41335174/46872121-200c0200-ce55-11e8-800c-91b7f75b041a.png)

**Comment by nikitastepan0v** [comment]
Wine version 3.17

**Comment by ChazizYT** [comment]
Get a Virtual Machine and Install both Steam and SAM. You do not need your games to be installed.

Wine is still incomplete.
