### ISSUE TITLE
同时运行200个窗口挂游戏，电脑会非常的卡，没有CPU与内存的占用，他占用是非常空闲的，这是为什么？

### ISSUE THREAD

**Issue by 1265578519** [gibbed/SteamAchievementManager#98]
同时运行200个窗口挂游戏，电脑会非常的卡，没有CPU与内存的占用，他占用是非常空闲的，这是为什么？

**Comment by gibbed** [comment]
Sorry, I can't read Chinese and unfortunately Google Translate isn't helping me here either.

**Comment by Isopach** [comment]
@gibbed, @1265578519 is saying that running 200 instances of games from SAM will make the computer so slow that it becomes unusable. This is despite having lots of RAM, and he wonders why the program isn't using it efficiently.

**Comment by 1265578519** [comment]
我知道了，是进程多了，导致windows的句柄过多导致、

**Comment by gibbed** [comment]
That's way beyond intended usage of SAM, I'm not sure what your intent is behind doing that. If it's idling games, [there are better tools for that](https://github.com/jshackles/idle_master).

**Comment by 1265578519** [comment]
谢谢，我主要用来挂卡牌和在线时间。

**Comment by AngelaPohuyzier** [comment]
https://github.com/JustArchiNET/ArchiSteamFarm/releases idle master was abandoned project
