### ISSUE TITLE
[Request] Unlock achievements in specific time

### ISSUE THREAD

**Issue by Carje4cs** [gibbed/SteamAchievementManager#99]
What I mean is that it will be nice if we can choose in what period of time, achievements to be unlocked (eg. 1 hour), and divide the number of achievements to this timeframe (± random time).

This is just for cleaner stats view (in my opinion).

Advanced - Smart
For an more advanced way, you can make this feature smart by taking the stats per game:
Hours needed to be played for "Completionist" -> [HowLongToBeat](https://howlongtobeat.com)
Global achievements from steam api -> [SteamApi](https://api.steampowered.com/ISteamUserStats/GetGlobalAchievementPercentagesForApp/v2/?gameid={appid})
This way it can take the average play hours to get all the achievements and order them from most earned to least.

**Comment by gibbed** [comment]
This isn't possible via the public facing Steam API without actually waiting out these times, which is out of scope for SAM.
